Repository pyccel/pyccel, pull requests merged in 2020-12, with the labels that each got.

#595 Use ternary operator instead of modulo to handle negative indices
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
Labels: Ready_to_merge

#598 Create missing gfortran symbolic link on macOS
  .github/actions/macos_install/action.yml
Labels: Ready_to_merge

#597 Fix MPI tests on Windows
  .github/actions/windows_install/action.yml
  .github/workflows/Github_pytest.yml
  pyccel/epyccel.py
Labels: Ready_to_merge

#600 Add printing methods to operators and literals
  pyccel/ast/literals.py
  pyccel/ast/operators.py
  pyccel/parser/semantic.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Ready_for_review

#574 Add simple Garbage collector to C printer / raise errors in some array assignment cases
  .gitignore
  pyccel/ast/core.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
  pyccel/stdlib/ndarrays/ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.h
  tests/codegen/ccode/scripts/arrays_pointers.py
  tests/codegen/ccode/test_ccode_codegen.py
  tests/epyccel/modules/pointers.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_arrays_multiple_assignments.py
  tests/epyccel/test_pointers.py
  tests/ndarrays/test_ndarrays.c
Labels: Ready_to_merge

#599 Handle Duplicated header of a function
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/generic_functions_2.py
  tests/epyccel/test_generic_functions.py
Labels: Ready_to_merge

#612 Correct Dlist so it works with any ordering
  pyccel/parser/semantic.py
  tests/epyccel/modules/tuples.py
Labels: Ready_to_merge

#613 Raise an error when encountering an inhomogenous list
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
  tests/errors/semantic/blocking/INHOMOG_LIST.py
  tests/warnings/test_warnings.py
Labels: Ready_to_merge

#614 Catch DottedVariable TypeError
  pyccel/ast/core.py
  pyccel/parser/semantic.py
  tests/errors/semantic/blocking/str_join.py
  tests/errors/semantic/blocking/str_join2.py
Labels: Ready_to_merge

#617 Fix import error in tutorial on header files
  tutorial/header-files.md
Labels: Ready_to_merge

#618 Remove leading '' // in Fortran print statements
  pyccel/codegen/printing/fcode.py
Labels: Ready_to_merge

#621 Fortran: print PythonLen as size or len depending on dtype
  pyccel/codegen/printing/fcode.py
Labels: Language:Fortran, Ready_to_merge

#615 Handle order property
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/numpyext.py
  pyccel/ast/operators.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
Labels: Ready_to_merge

#630 Add safeguard against malicious exploitation of ISO_C_BINDING import
  pyccel/codegen/printing/fcode.py
Labels: Language:Fortran, Ready_to_merge

#625 Make Fortran printer handle numpy.array when rank > 2
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
Labels: Language:Fortran, Ready_to_merge

#626 Allow slices with negative step in C
  pyccel/codegen/printing/ccode.py
  pyccel/stdlib/ndarrays/ndarrays.h
  tests/pyccel/scripts/arrays_view.py
  tests/pyccel/test_pyccel.py
Labels: Language:C

#631 Support Python style type hints
  pyccel/ast/core.py
  pyccel/errors/messages.py
  pyccel/parser/syntactic.py
  tests/epyccel/modules/python_annotations.py
  tests/epyccel/test_epyccel_python_annotations.py
Labels: Ready_to_merge

#638 Exempt AugAssign from raising reassigning errors
  pyccel/parser/semantic.py
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
Labels: Ready_to_merge
