Repository pyccel/pyccel, pull requests merged in 2021-03, with the labels that each got.

#763 Fix bugs in numpy imag
  pyccel/ast/literals.py
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/ccode.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Language:Fortran, Ready_to_merge, bug

#779 Handle bool arguments in numpy.mod
  pyccel/ast/numpyext.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Language:Fortran, Ready_to_merge, bug

#777 Fix bugs in numpy.prod
  pyccel/ast/numpyext.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Language:Fortran, Ready_to_merge, bug

#776 Handle int8 int16 bool
  pyccel/ast/numpyext.py
  pyccel/parser/semantic.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Ready_to_merge

#593 Extend OpenMP support by adding more pragmas
  pyccel/ast/core.py
  pyccel/ast/omp.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/grammar/openmp.tx
  pyccel/parser/semantic.py
  pyccel/parser/syntax/openmp.py
  tests/epyccel/modules/openmp.py
  tests/epyccel/test_epyccel_openmp.py
  tutorial/openmp.md
Labels: Ready_to_merge

#781 Remove Sympy inheritance from printers
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/codeprinter.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
Labels: Ready_to_merge, internals

#775 Print abs function in C
  pyccel/codegen/printing/ccode.py
  tests/epyccel/test_builtins.py
Labels: Ready_to_merge

#782 Add short traceback to generated errors in developer mode
  pyccel/epyccel.py
  pyccel/errors/errors.py
  pyccel/parser/semantic.py
  tests/epyccel/conftest.py
Labels: Ready_to_merge, enhancement, internals

#787 Bugfix: Correct return type of `float` with boolean argument
  pyccel/ast/builtins.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Ready_to_merge, bug

#793 Improve setup_X.py file
  pyccel/codegen/cwrapper.py
Labels: enhancement, internals, needs_initial_review

#783 Complete python printer to enable epyccel tests
  .github/actions/pytest_run/action.yml
  .github/workflows/Github_pytest.yml
  .github/workflows/master.yml
  pyccel/ast/basic.py
  pyccel/ast/core.py
  pyccel/ast/numpyext.py
  pyccel/codegen/pipeline.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/epyccel/conftest.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_arrays_multiple_assignments.py
  tests/epyccel/test_base.py
  tests/epyccel/test_epyccel_decorators.py
  tests/epyccel/test_epyccel_default_args.py
  tests/epyccel/test_epyccel_division.py
  tests/epyccel/test_epyccel_openmp.py
  tests/epyccel/test_epyccel_optional_args.py
  tests/epyccel/test_generic_functions.py
Labels: Language:Python, Ready_to_merge

#780 Allow negative step in for loops
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/modules/loops.py
  tests/epyccel/test_loops.py
Labels: Ready_to_merge

#796 Add __slots__ to classes in AST
  .github/actions/pytest_run/action.yml
  .github/actions/pytest_run_python/action.yml
  .github/workflows/Github_pytest.yml
  .github/workflows/master.yml
  pyccel/ast/basic.py
  pyccel/ast/bitwise_operators.py
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/datatypes.py
  pyccel/ast/functionalexpr.py
  pyccel/ast/headers.py
  pyccel/ast/internals.py
  pyccel/ast/itertoolsext.py
  pyccel/ast/literals.py
  pyccel/ast/macros.py
  pyccel/ast/mathext.py
  pyccel/ast/numpyext.py
  pyccel/ast/omp.py
  pyccel/ast/operators.py
  pyccel/ast/variable.py
  pyccel/version.py
Labels: Ready_for_review

#788 Handle OpenMP differences between C and Fortran
  pyccel/ast/core.py
  pyccel/ast/omp.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/grammar/openmp.tx
  pyccel/parser/semantic.py
  pyccel/parser/syntax/openmp.py
  tests/epyccel/modules/openmp.py
  tests/epyccel/test_epyccel_openmp.py
  tests/errors/semantic/blocking/OPENMP_loop_check.py
  tests/errors/semantic/blocking/OPENMP_parallel_for_check.py
  tests/errors/semantic/blocking/OPENMP_simd_check.py
  tests/preprocess/scripts/omp.py
  tutorial/openmp.md
Labels: Ready_to_merge

#805 Fix bug in semantic parser when sliced array is modified in function call
  pyccel/ast/core.py
  pyccel/ast/literals.py
  pyccel/ast/variable.py
  pyccel/parser/semantic.py
  pyccel/version.py
  tests/epyccel/modules/Module_6.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_epyccel_modules.py
Labels: needs_initial_review

#795 Reduce number of calls to get_attribute_nodes
  pyccel/ast/basic.py
  pyccel/ast/core.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/complexity/memory.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
Labels: Ready_to_merge

#790 Fix numpy.norm bugs
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/codeprinter.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Language:Fortran, Ready_to_merge, bug

#807 Speed up unit tests by running them in parallel with pytest-xdist
  .github/actions/pip_installation/action.yml
  .github/actions/pytest_parallel/action.yml
  .github/actions/pytest_run/action.yml
  .github/actions/pytest_run_python/action.yml
  .github/workflows/Github_pytest.yml
  .github/workflows/master.yml
  README.rst
  pyccel/codegen/pipeline.py
  pyccel/codegen/python_wrapper.py
  pyccel/commands/console.py
  pyccel/commands/pyccel_clean.py
  pyccel/epyccel.py
  pyccel/parser/utilities.py
  pytest.ini
  setup.py
  tests/conftest.py
  tests/epyccel/conftest.py
  tests/epyccel/test_generic_functions.py
  tests/printers/__init__.py
  tests/printers/test_ccode.py
  tests/printers/test_fcode.py
  tests/printers/test_luacode.py
  tests/pyccel/test_pyccel.py
Labels: Ready_for_review

#719 Add tests for numpy functions
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/recognised_functions/test_numpy_types.py
Labels: Language:C, Language:Fortran, Language:Python, needs_initial_review

#818 Remove usage of deprecated Numpy types
  tests/epyccel/modules/arrays.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/recognised_functions/test_numpy_types.py
  tests/epyccel/test_epyccel_optional_args.py
  tests/epyccel/test_generic_functions.py
Labels: Ready_for_review

#822 Handle IndexedElement in multi-assign
  pyccel/ast/utilities.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/tuples.py
  tests/epyccel/test_tuples.py
Labels: Ready_to_merge

#817 Implement PythonLen in C
  pyccel/ast/builtins.py
  pyccel/codegen/printing/ccode.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_epyccel_openmp.py
Labels: Ready_to_merge

#819 Use numpy cast functions to cast arrays
  pyccel/ast/builtins.py
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/recognised_functions/test_numpy_types.py
Labels: Ready_for_review

#820 Fix min / max functions
  pyccel/ast/builtins.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_builtins.py
Labels: Ready_to_merge

#823 Speed up visit of PyccelAdd and PyccelMul nodes in semantic parser
  pyccel/parser/semantic.py
  pyccel/version.py
Labels: Ready_to_merge

#830 Ensure one-line statements in printers end with `\n
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/test_arrays.py
Labels: Ready_to_merge

#831 Remove unnecessary NativeOp class
  pyccel/ast/core.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/luacode.py
  pyccel/codegen/printing/pycode.py
Labels: needs_initial_review

#828 Raise error when function call has wrong number of arguments
  pyccel/ast/basic.py
  pyccel/parser/semantic.py
  tests/errors/semantic/blocking/TOO_MANY_ARGS.py
  tests/errors/semantic/non_blocking/TOO_FEW_ARGS.py
Labels: Ready_to_merge

#833 Add basic array printer to CCodePrinter
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#834 Fix AliasAssign of array in C
  pyccel/codegen/printing/ccode.py
Labels: Ready_to_merge

#832 Add FunctionalFor, Enumerate, Zip, and Map to C printer
  pyccel/ast/core.py
  pyccel/ast/datatypes.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/test_base.py
  tests/epyccel/test_compare_expressions.py
  tests/epyccel/test_loops.py
  tests/epyccel/utilities.py
Labels: Ready_to_merge
