Repository pyccel/pyccel, pull requests merged in 2021-04, with the labels that each got.

#841 Fix stack arrays in C
  pyccel/codegen/printing/ccode.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#848 Add printer for NumpyMod
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Ready_to_merge, needs_initial_review

#845 Fix memory allocation for nd stack array (n>1)
  pyccel/codegen/printing/ccode.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/pyccel/scripts/runtest_degree_in.py
Labels: Ready_to_merge

#846 Fix flattening the nd array when dim > 2
  pyccel/codegen/printing/ccode.py
  tests/epyccel/test_arrays.py
Labels: Ready_to_merge

#851 Set shape to PyccelArraySize if Variable is a pointer
  pyccel/ast/literals.py
  pyccel/ast/operators.py
  pyccel/ast/variable.py
  tests/epyccel/modules/pointers.py
Labels: Ready_to_merge, needs_initial_review

#797 Allow simplification of pyccel-created nodes
  .gitignore
  pyccel/ast/bitwise_operators.py
  pyccel/ast/operators.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/version.py
Labels: Ready_to_merge

#842 Clean up tuples and fix Dlist (renamed as Duplicate)
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/literals.py
  pyccel/ast/operators.py
  pyccel/ast/sympy_helper.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/tuples.py
  tests/epyccel/test_tuples.py
Labels: Ready_for_review

#852 Remove useless statements and raise a warning
  pyccel/ast/core.py
  pyccel/parser/semantic.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/warnings/semantic/USELESS_EXPRESSION.py
Labels: Ready_to_merge

#860 Reorder OpenMP installation in Ubuntu
  .github/actions/linux_install/action.yml
Labels: Ready_to_merge

#826 Numpy functions tutorial
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tutorial/ndarrays.md
  tutorial/numpy-functions.md
Labels: Ready_to_merge, documentation

#877 Raise an error if an argument with the wrong dtype/precision/rank is passed to a function
  pyccel/ast/headers.py
  pyccel/ast/macros.py
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
  pyccel/parser/syntax/headers.py
  tests/errors/semantic/non_blocking/INCOMPATIBLE_ARGUMENT.py
  tests/errors/semantic/non_blocking/INCOMPATIBLE_ARGUMENT2.py
  tests/internal/scripts/lapack/ex1.py
Labels: Ready_for_review

#878 Improve indenting of Fortran code
  pyccel/codegen/printing/fcode.py
Labels: Ready_for_review

#880 Do not use shell=True in subprocess calls
  .github/workflows/Github_pytest.yml
  .github/workflows/master.yml
  pyccel/codegen/pipeline.py
  pyccel/codegen/python_wrapper.py
  pyccel/codegen/utilities.py
Labels: Ready_for_review

#884 Treat extra spaces in flag options
  pyccel/codegen/pipeline.py
  tests/epyccel/test_return.py
Labels: Ready_to_merge
