Repository pyccel/pyccel, pull requests merged in 2021-05, with the labels that each got.

#875 Fix 1D-1D matmul bug
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tutorial/numpy-functions.md
Labels: Language:C, Ready_to_merge, bug, internals

#883 Replace get_index with inline strides
  pyccel/codegen/printing/ccode.py
  pyccel/errors/messages.py
  pyccel/stdlib/ndarrays/ndarrays.h
Labels: Ready_to_merge

#887 Fix GCC naming in README file
  README.rst
Labels: Ready_to_merge

#889 Remove obsolete functions `build_types_decorator` and `_construct_header`
  pyccel/ast/utilities.py
  pyccel/codegen/printing/pycode.py
Labels: Ready_to_merge

#890 Add Matmul operator
  pyccel/ast/numpyext.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
Labels: Ready_to_merge

#862 Match results of integer modulo operations between languages.
  pyccel/codegen/printing/ccode.py
  pyccel/stdlib/math/pyc_math.h
  tests/epyccel/test_epyccel_mod.py
Labels: Language:C, Ready_to_merge, bug

#837 Do not require that there is a comment before an else block
  .github/actions/macos_install/action.yml
  .github/actions/pip_installation/action.yml
  README.rst
  pyccel/parser/extend_tree.py
  tests/epyccel/modules/openmp.py
  tests/epyccel/test_epyccel_openmp.py
  tests/parser/scripts/comments.py
  tests/parser/test_comments.py
  tests/syntax/test_syntax.py
Labels: Ready_to_merge

#872 Fix Python printer and test it
  .github/actions/pytest_run_python/action.yml
  pyccel/codegen/printing/pycode.py
  tests/epyccel/test_epyccel_openmp.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#893 Fix aliases in python printing. Add name attribute to PyccelInternalFunctions
  .github/actions/macos_install/action.yml
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/internals.py
  pyccel/ast/itertoolsext.py
  pyccel/ast/mathext.py
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/errors/semantic/blocking/IMPORTING_EXISTING_IDENTIFIED2.py
  tests/errors/semantic/blocking/IMPORTING_EXISTING_IDENTIFIED3.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#898 Fix complex cast bug
  pyccel/codegen/printing/fcode.py
  tests/epyccel/modules/complex_func.py
  tests/epyccel/test_epyccel_complex_func.py
Labels: Language:Fortran, needs_initial_review

#901 Fix empty returns
  pyccel/ast/core.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/syntactic.py
  tests/epyccel/test_return.py
Labels: needs_initial_review

#902 Allow stand-alone expressions
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/codegen/fcode/scripts/USELESS_EXPRESSION.py
  tests/epyccel/modules/Module_7.py
  tests/epyccel/modules/tuples.py
  tests/epyccel/test_epyccel_modules.py
Labels: Ready_to_merge

#903 Improve error messages
  pyccel/ast/builtin_imports.py
  pyccel/ast/builtins.py
  pyccel/ast/utilities.py
  pyccel/errors/messages.py
  pyccel/parser/base.py
  pyccel/parser/semantic.py
  tests/errors/semantic/blocking/UNRECOGNISED_FUNCTION_CALL.py
  tests/errors/semantic/non_blocking/UNKNOWN_IMPORT.py
  tests/errors/semantic/non_blocking/UNKNOWN_IMPORT2.py
Labels: Ready_for_review

#905 Set syntactic_only for .pyh files
  pyccel/codegen/pipeline.py
  tests/pyccel/scripts/basic_header.pyh
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge
