Repository pyccel/pyccel, pull requests merged in 2021-08, with the labels that each got.

#928 Clean compilation
  .gitignore
  pyccel/codegen/compiling/__init__.py
  pyccel/codegen/compiling/basic.py
  pyccel/codegen/compiling/compilers.py
  pyccel/codegen/cwrapper.py
  pyccel/codegen/pipeline.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/python_wrapper.py
  pyccel/codegen/utilities.py
  pyccel/commands/console.py
  pyccel/compilers/__init__.py
  pyccel/compilers/generate_default.py
  pyccel/epyccel.py
  pyccel/parser/base.py
  pyccel/parser/parser.py
  pyccel/stdlib/math/pyc_math_c.c
  pyccel/stdlib/math/pyc_math_c.h
  pyccel/stdlib/math/pyc_math_f90.f90
  pyccel/version.py
  tests/epyccel/test_epyccel_openmp.py
  tests/internal/test_internal.py
  tutorial/compiler.md
Labels: Ready_to_merge

#921 Ensure pyccel knows when shape is not known
  pyccel/ast/variable.py
  pyccel/parser/semantic.py
  tests/epyccel/test_arrays_multiple_assignments.py
Labels: Ready_to_merge

#934 Raise specific error for (re)allocating array arguments
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
Labels: Ready_to_merge

#886 Wrapper part 1 (create C library for wrapper functions)
  pyccel/ast/bind_c.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/numpy_wrapper.py
  pyccel/ast/numpyext.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/compiling/basic.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/python_wrapper.py
  pyccel/codegen/utilities.py
  pyccel/epyccel.py
  pyccel/parser/utilities.py
  pyccel/stdlib/cwrapper/cwrapper.c
  pyccel/stdlib/cwrapper/cwrapper.h
  pyccel/stdlib/cwrapper/cwrapper_ndarrays.c
  pyccel/stdlib/cwrapper/cwrapper_ndarrays.h
  pyccel/stdlib/ndarrays/ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.h
  tests/ndarrays/test_ndarrays.c
Labels: Ready_to_merge

#935 Add missing copy to macros expecting arguments to occur in results
  pyccel/ast/headers.py
  pyccel/codegen/compiling/basic.py
  pyccel/codegen/compiling/compilers.py
  pyccel/codegen/pipeline.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntax/headers.py
  pyccel/stdlib/internal/blas.pyh
  pyccel/stdlib/internal/lapack.pyh
  pyccel/stdlib/internal/openmp.pyh
  tests/external/scripts/lapack/ex1.py
  tests/external/test_external.py
Labels: Ready_to_merge

#939 Add transpose function
  pyccel/ast/class_defs.py
  pyccel/ast/numpyext.py
  pyccel/ast/operators.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  pyccel/stdlib/ndarrays/ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.h
  tests/epyccel/test_epyccel_transpose.py
Labels: Ready_to_merge

#946 Make cwrapper type check functions static inline (python>=3.9)
  pyccel/stdlib/cwrapper/cwrapper.h
Labels: needs_initial_review

#922 Convert IfTernaryOperator returning array or string to If block
  .github/actions/pytest_run/action.yml
  pyccel/ast/numpyext.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/parser/semantic.py
  tests/epyccel/test_arrays_multiple_assignments.py
  tests/epyccel/test_epyccel_IfTernaryOperator.py
Labels: Ready_to_merge

#944 Improve test reliability
  .github/actions/coverage_install/action.yml
  tests/epyccel/recognised_functions/test_epyccel_pyc_math.py
  tests/epyccel/recognised_functions/test_math_funcs.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_epyccel_default_args.py
  tests/epyccel/test_epyccel_division.py
  tests/epyccel/test_epyccel_functions.py
  tests/epyccel/test_epyccel_mod.py
  tests/epyccel/test_epyccel_modules.py
  tests/epyccel/test_epyccel_pow.py
  tests/epyccel/test_parallel_epyccel.py
Labels: Ready_to_merge

#941 Add shortcuts to Fortran literals
  pyccel/ast/datatypes.py
  pyccel/codegen/printing/fcode.py
  tests/pyccel/scripts/expressions.py
Labels: Ready_to_merge

#938 Update compilation configuration
  pyccel/compilers/generate_default.py
  pyccel/version.py
Labels: Ready_to_merge

#952 Stop mac warnings due to incompatible dylib files
  pyccel/codegen/compiling/compilers.py
Labels: Ready_for_review

#908 Clear up ambiguity by removing ValuedVariable
  pyccel/ast/bind_c.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/headers.py
  pyccel/ast/numpyext.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/commands/pyccel_clean.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/parser/syntax/headers.py
  tests/ast/test_basic.py
  tests/epyccel/test_base.py
  tests/epyccel/test_epyccel_default_args.py
  tests/epyccel/test_epyccel_optional_args.py
  tests/macro/scripts/lapack/dgbtrf.py
  tests/pyccel/scripts/default_args_mod.py
  tests/pyccel/scripts/runtest_default_args.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge
