Repository pyccel/pyccel, pull requests merged in 2021-11, with the labels that each got.

#1019 Allow `import mod` syntax for a header file
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  tests/internal/scripts/blas/ex5.py
Labels: needs_initial_review

#1009 Stop unnecessary loop unrolling
  pyccel/ast/utilities.py
Labels: Ready_to_merge

#1021 Fix external function call from function in function
  pyccel/codegen/printing/fcode.py
  tests/epyccel/modules/external_functions.py
  tests/epyccel/test_external_functions.py
Labels: bug, Ready_to_merge

#998 Add table of contents and documentation index to README file
  README.md
  README.rst
  setup.py
  tutorial/templates.md
Labels: Ready_to_merge

#1012 Rename real->float in pyccel code
  pyccel/ast/bitwise_operators.py
  pyccel/ast/builtins.py
  pyccel/ast/class_defs.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/datatypes.py
  pyccel/ast/literals.py
  pyccel/ast/mathext.py
  pyccel/ast/numpy_wrapper.py
  pyccel/ast/numpyext.py
  pyccel/ast/operators.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#1014 Fix default arguments for non-default precisions
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/Module_8.py
  tests/epyccel/test_epyccel_default_args.py
Labels: Ready_to_merge

#1015 Allow optional arrays in C
  pyccel/codegen/printing/ccode.py
  tests/epyccel/test_epyccel_optional_args.py
Labels: Ready_to_merge

#1026 Fix confusion between FunctionKind/Static and the name of the Function in the grammar
  pyccel/parser/grammar/headers.tx
  tests/epyccel/modules/highorder_functions.py
Labels: Ready_to_merge

#838 Fix Numpy linspace bug and raise error for Numpy where arguments
  pyccel/ast/numpyext.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
  pyccel/version.py
  tests/epyccel/modules/highorder_functions.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/errors/semantic/blocking/NUMPY_WHERE_SINGLE_ARGUMENT.py
  tutorial/numpy-functions.md
Labels: Ready_to_merge

#1004 Developer docs
  README.md
  developer_docs/how_to_solve_an_issue.md
  developer_docs/overview.md
  developer_docs/review_process.md
  developer_docs/tips_and_tricks.md
  pyccel/errors/errors.py
Labels: Ready_for_review

#1034 Initialise ndarrays at NULL
  pyccel/codegen/printing/ccode.py
  tests/ndarrays/leaks_check.py
Labels: Ready_to_merge

#989 adding docs for functions-as-arguments feature
  README.md
  tutorial/function-pointers-as-arguments.md
Labels: Ready_to_merge

#1024 Add documentation for const keyword
  README.md
  tutorial/const_keyword.md
Labels: Ready_to_merge

#1017 Add inline decorator to pyccel
  pyccel/ast/basic.py
  pyccel/ast/core.py
  pyccel/ast/internals.py
  pyccel/ast/literals.py
  pyccel/ast/numpyext.py
  pyccel/ast/operators.py
  pyccel/ast/utilities.py
  pyccel/codegen/codegen.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/decorators.py
  pyccel/errors/messages.py
  pyccel/parser/base.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/epyccel/test_epyccel_decorators.py
  tests/epyccel/test_epyccel_generators.py
  tests/internal/scripts/blas/ex5.py
  tests/pyccel/scripts/decorators_inline.py
  tests/pyccel/scripts/runtest_decorators_inline.py
  tests/pyccel/test_pyccel.py
  tutorial/decorators.md
Labels: Ready_for_review

#1013 Add dummy variables where necessary to avoid aliasing in Fortran
  pyccel/ast/basic.py
  pyccel/codegen/printing/fcode.py
  tests/pyccel/scripts/runtest_function_alias.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#1046 Improve imports to allow importing inline functions
  pyccel/ast/bind_c.py
  pyccel/ast/core.py
  pyccel/ast/itertoolsext.py
  pyccel/ast/mathext.py
  pyccel/ast/numpyext.py
  pyccel/ast/scipyext.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/codegen.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/errors/errors.py
  pyccel/parser/base.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/stdlib/internal/lapack.pyh
  tests/pyccel/scripts/decorators_inline.py
  tests/pyccel/scripts/runtest_decorators_inline.py
  tests/pyccel/test_pyccel.py
  tutorial/decorators.md
Labels: Ready_to_merge
