Repository pyccel/pyccel, pull requests merged in 2021-01, with the labels that each got.

#602 Add tests of memory leaks to GitHub actions
  .github/actions/linux_install/action.yml
  .github/actions/macos_install/action.yml
  .github/actions/valgrind_run/action.yml
  .github/workflows/Github_pytest.yml
  tests/ndarrays/leaks_check.py
Labels: Ready_to_merge

#646 Stop using DottedVariable to store FunctionCall objects (fixes basic classes)
  pyccel/ast/core.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/pyccel/scripts/classes/classes.py
  tests/pyccel/scripts/classes/classes_1.py
  tests/pyccel/scripts/classes/classes_5.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#659 Move Nil class from ast.core to ast.literals
  pyccel/ast/core.py
  pyccel/ast/literals.py
  pyccel/ast/numpyext.py
  pyccel/ast/operators.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
Labels: Ready_to_merge

#652 Allow translating from python to python
  .github/actions/pytest_run/action.yml
  pyccel/codegen/pipeline.py
  pyccel/codegen/printing/pycode.py
  pyccel/commands/console.py
  pyccel/epyccel.py
  tests/epyccel/test_epyccel_functions.py
Labels: Ready_to_merge

#647 Remove IndexedVariable type
  pyccel/ast/bind_c.py
  pyccel/ast/core.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
Labels: Ready_to_merge

#655 Remove `sympy.Function` from pyccel
  pyccel/ast/basic.py
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/internals.py
  pyccel/ast/mathext.py
  pyccel/ast/numpyext.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
Labels: Ready_to_merge, needs_initial_review

#674 Describe usage of Pyccel container image
  README.rst
Labels: Ready_to_merge

#651 Set precedence of IfTernaryOperator
  pyccel/ast/core.py
  pyccel/ast/datatypes.py
  pyccel/ast/operators.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/epyccel/test_epyccel_IfTernaryOperator.py
Labels: Ready_to_merge

#645 Keep hidden imports
  pyccel/ast/core.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/epyccel/test_imports.py
Labels: Ready_to_merge

#637 Create ast.variable and bug fixes
  pyccel/ast/bind_c.py
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/datatypes.py
  pyccel/ast/headers.py
  pyccel/ast/internals.py
  pyccel/ast/literals.py
  pyccel/ast/mathext.py
  pyccel/ast/numpyext.py
  pyccel/ast/operators.py
  pyccel/ast/sympy_helper.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/parser/syntax/headers.py
  pyccel/parser/utilities.py
Labels: Ready_to_merge

#675 Bugfix: create view from another view
  pyccel/parser/semantic.py
  tests/pyccel/scripts/arrays_view.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#673 Add print_kind method to Fortran printer
  pyccel/codegen/printing/fcode.py
Labels: Language:Fortran, enhancement

#676 Remove sympy.Tuple from pyccel's AST representation
  pyccel/ast/bind_c.py
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/headers.py
  pyccel/ast/itertoolsext.py
  pyccel/ast/numpyext.py
  pyccel/ast/sympy_helper.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/complexity/arithmetic.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/parser/syntax/headers.py
  pyccel/symbolic/lambdify.py
Labels: Ready_to_merge

#629 Better handling for array slicing with literal indexes
  pyccel/codegen/printing/ccode.py
  pyccel/stdlib/ndarrays/ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.h
  tests/ndarrays/test_ndarrays.c
  tests/pyccel/scripts/arrays_view.py
Labels: Ready_to_merge

#671 Ndarray starter guide
  tutorial/ndarrays.md
Labels: Ready_to_merge, documentation

#679 Follow C style convention for include syntax
  pyccel/codegen/printing/ccode.py
Labels: Language:C, Ready_to_merge, enhancement

#680 Raise correct error when pointer variable should own data
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
Labels: Ready_to_merge

#681 Accept Variable as argument for NumpyArray
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/ccode.py
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
  tests/errors/semantic/blocking/INIT_NDARRAY_WITH_INHOMOG_LIST.py
  tests/pyccel/scripts/c_arrays.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#684 Remove unused valgrind installation from macOS
  .github/actions/macos_install/action.yml
Labels: Ready_to_merge

#632 Add support of Numpy arrays as function arguments in C language
  pyccel/ast/cwrapper.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/stdlib/ndarrays/ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.h
  tests/epyccel/test_array_as_func_args.py
  tests/epyccel/test_epyccel_modules.py
  tests/epyccel/test_epyccel_python_annotations.py
  tests/epyccel/test_loops.py
  tests/ndarrays/test_ndarrays.c
Labels: Ready_to_merge

#669 Improve shape comparison in arithmetic operations
  pyccel/ast/operators.py
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
  tests/errors/semantic/blocking/ADD_ARRAYS_INCOMPATIBLE_SHAPES_0.py
  tests/errors/semantic/blocking/ADD_ARRAYS_INCOMPATIBLE_SHAPES_1.py
Labels: Ready_to_merge

#685 Remove `strict` argument which causes `sympify` to be called
  pyccel/ast/core.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/symbolic/lambdify.py
Labels: Ready_to_merge

#693 Add `__index__` magic method to `LiteralInteger`
  pyccel/ast/builtins.py
  pyccel/ast/literals.py
  pyccel/ast/variable.py
  pyccel/parser/semantic.py
Labels: Ready_to_merge

#627 Correctly calculate the shape of slice
  pyccel/ast/variable.py
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
Labels: Ready_to_merge

#622 Add quickstart.md file to documentation
  README.rst
  tutorial/quickstart.md
Labels: Ready_to_merge, documentation

#701 Ensure inserted imports are ignored by C/Fortran printers
  pyccel/parser/semantic.py
  pyccel/version.py
  tests/epyccel/test_imports.py
Labels: Ready_to_merge, bug

#704 Remove sympy indexed
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/variable.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/symbolic/lambdify.py
Labels: Ready_for_review, internals

#707 Handle `if n:` for an optional argument `n`
  pyccel/ast/bitwise_operators.py
  pyccel/ast/builtins.py
  pyccel/ast/operators.py
  pyccel/parser/syntactic.py
  tests/epyccel/modules/base.py
  tests/epyccel/test_base.py
Labels: Ready_to_merge

#712 Remove unused classes in ast/core.py and ast/datatypes.py
  pyccel/ast/core.py
  pyccel/ast/datatypes.py
  pyccel/ast/numpyext.py
  pyccel/codegen/codegen.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/complexity/arithmetic.py
  pyccel/complexity/memory.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
Labels: Ready_to_merge

#713 Make classes in ast/core.py mutable
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/base.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/symbolic/lambdify.py
Labels: Ready_to_merge

#711 Add numpy arange
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
Labels: Ready_to_merge
