Repository pyccel/pyccel, pull requests merged in 2021-02, with the labels that each got.

#683 Access templates of a function via its decorators
  pyccel/ast/core.py
  pyccel/codegen/printing/pycode.py
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
Labels: Language:C, Ready_to_merge, internals

#708 Fix result type of floor division, math ceil function and the wrong result of math floor of negative float in C
  pyccel/codegen/printing/ccode.py
  tests/epyccel/recognised_functions/test_math_funcs.py
  tests/epyccel/test_epyccel_division.py
Labels: Language:C, Ready_to_merge, bug

#710 Add stack_arrays in C
  pyccel/codegen/printing/ccode.py
  pyccel/stdlib/ndarrays/ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.h
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
Labels: Ready_to_merge

#717 Make more AST classes mutable
  pyccel/ast/functionalexpr.py
  pyccel/ast/headers.py
  pyccel/ast/itertoolsext.py
  pyccel/errors/errors.py
Labels: Ready_to_merge

#714 Add casting to get_index when needed.
  pyccel/codegen/printing/ccode.py
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
  pyccel/stdlib/ndarrays/ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.h
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
Labels: Language:C, Ready_to_merge

#721 Support shape overriding on full/empty/ones/zeros_like functions
  pyccel/ast/numpyext.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Language:C, Language:Fortran, Ready_to_merge, enhancement

#725 Add IfSection class
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
Labels: Ready_to_merge

#726 Use mutable objects in classes instead of indexing _args
  pyccel/ast/builtins.py
  pyccel/ast/datatypes.py
  pyccel/ast/internals.py
  pyccel/ast/literals.py
  pyccel/ast/macros.py
  pyccel/ast/numpyext.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
Labels: Ready_for_review

#724 Handle type casting in array_fill
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/ccode.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Language:C, Ready_for_review

#728 Add magic method __bool__ to Nil class
  pyccel/ast/literals.py
  pyccel/ast/numpyext.py
Labels: Ready_to_merge, enhancement

#732 Reduce sympy dependence
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/headers.py
  pyccel/ast/literals.py
  pyccel/ast/macros.py
  pyccel/ast/numpyext.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/codeprinter.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/parser/syntax/headers.py
Labels: Ready_to_merge

#716 Drop Sympy's Symbol
  pyccel/ast/bind_c.py
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/headers.py
  pyccel/ast/internals.py
  pyccel/ast/macros.py
  pyccel/ast/operators.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/codeprinter.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/base.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/parser/syntax/headers.py
  pyccel/parser/utilities.py
  pyccel/symbolic/lambdify.py
Labels: Ready_to_merge

#718 Improve `pyccel.ast.basic.Basic` to contain context information and helper functions
  .github/actions/pytest_run/action.yml
  .github/workflows/Github_pytest.yml
  .github/workflows/master.yml
  pyccel/ast/basic.py
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/datatypes.py
  pyccel/ast/functionalexpr.py
  pyccel/ast/headers.py
  pyccel/ast/internals.py
  pyccel/ast/itertoolsext.py
  pyccel/ast/literals.py
  pyccel/ast/macros.py
  pyccel/ast/numpyext.py
  pyccel/ast/operators.py
  pyccel/ast/sympy_helper.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/luacode.py
  pyccel/complexity/arithmetic.py
  pyccel/complexity/memory.py
  pyccel/errors/errors.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/ast/README.rst
  tests/ast/scripts/math.py
  tests/ast/test_ast.py
  tests/ast/test_basic.py
  tests/ast/test_parallel.py
  tests/errors/known_bugs/dicts.py
  tests/errors/syntax_blockers/dict_str_keys.py
  tests/errors/syntax_blockers/ex1.py
  tests/errors/syntax_blockers/import_star.py
Labels: Ready_to_merge, internals

#730 Fix passing array_like argument to numpy real function
  pyccel/ast/builtins.py
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Language:Fortran, bug

#744 [BUGFIX] Break infinite recursion
  pyccel/ast/basic.py
  pyccel/parser/semantic.py
  tests/ast/scripts/cyclic_dependence.py
  tests/ast/test_basic.py
Labels: Ready_to_merge

#623 Unravel loops when necessary
  .pylintrc
  pyccel/ast/basic.py
  pyccel/ast/core.py
  pyccel/ast/internals.py
  pyccel/ast/numpyext.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/epyccel/modules/multi_rank.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_arrays_multiple_assignments.py
  tests/epyccel/test_base.py
  tests/epyccel/test_compare_expressions.py
  tests/epyccel/test_epyccel_IfTernaryOperator.py
  tests/epyccel/test_epyccel_default_args.py
  tests/epyccel/test_epyccel_functions.py
  tests/epyccel/test_epyccel_modules.py
  tests/epyccel/test_epyccel_multi_rank.py
  tests/epyccel/test_epyccel_openmp.py
  tests/epyccel/test_epyccel_optional_args.py
  tests/epyccel/test_epyccel_python_annotations.py
  tests/epyccel/test_generic_functions.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#762 Remove Sympy inheritance from AST nodes
  pyccel/ast/basic.py
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/datatypes.py
  pyccel/ast/functionalexpr.py
  pyccel/ast/headers.py
  pyccel/ast/internals.py
  pyccel/ast/itertoolsext.py
  pyccel/ast/literals.py
  pyccel/ast/macros.py
  pyccel/ast/numpyext.py
  pyccel/ast/operators.py
  pyccel/ast/variable.py
  pyccel/codegen/codegen.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/errors/errors.py
  pyccel/parser/semantic.py
  pyccel/utilities/__init__.py
  pyccel/utilities/metaclasses.py
  tests/epyccel/test_parallel_epyccel.py
  tests/pyccel/test_pyccel.py
Labels: Ready_for_review

#759 Correctly handle scalar Numpy arguments in C wrapper
  pyccel/ast/cwrapper.py
  pyccel/codegen/printing/cwrappercode.py
  tests/epyccel/modules/types.py
  tests/epyccel/recognised_functions/test_math_funcs.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_base.py
  tests/epyccel/test_epyccel_functions.py
  tests/epyccel/test_epyccel_openmp.py
  tests/epyccel/test_epyccel_python_annotations.py
  tests/epyccel/test_epyccel_types.py
  tests/epyccel/test_generic_functions.py
  tests/epyccel/test_kind.py
Labels: Ready_to_merge

#750 Avoid printing unused variables in C
  pyccel/ast/core.py
  pyccel/ast/internals.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/epyccel/test_return.py
Labels: Language:C, Ready_to_merge, enhancement

#764 Store LiteralInteger value in a private variable
  pyccel/ast/builtins.py
  pyccel/ast/literals.py
  pyccel/ast/sympy_helper.py
  pyccel/parser/semantic.py
Labels: Ready_to_merge

#755 Fix casting boolean in numpy float/complex
  pyccel/ast/builtins.py
  pyccel/codegen/printing/ccode.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Language:C, Ready_to_merge, bug
