Repository pyccel/pyccel, pull requests merged in 2021-09, with the labels that each got.

#954 Activate mpi tests on windows
  .github/actions/windows_install/action.yml
  pyccel/compilers/generate_default.py
  pyccel/epyccel.py
  tests/internal/test_internal.py
Labels: Ready_to_merge

#948 Add shape of results to macro language to avoid unnecessary variable declarations
  pyccel/ast/headers.py
  pyccel/errors/messages.py
  pyccel/parser/grammar/headers.tx
  pyccel/parser/semantic.py
  pyccel/parser/syntax/headers.py
  pyccel/stdlib/external/lapack.py
  tests/external/scripts/lapack/ex1.py
  tests/macro/scripts/blas/daxpy.py
  tests/macro/scripts/blas/dcopy.py
  tests/macro/scripts/blas/dgemm.py
  tests/macro/scripts/blas/dgemv.py
  tests/macro/scripts/blas/dger.py
  tests/macro/scripts/blas/dscal.py
  tests/macro/scripts/blas/dswap.py
  tests/macro/scripts/lapack/dgbtrf.py
Labels: Ready_to_merge

#957 Wrapper part 2 (Treat C and Fortran arrays similarly in wrapper)
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/numpy_wrapper.py
  pyccel/codegen/pipeline.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/python_wrapper.py
  pyccel/codegen/utilities.py
  pyccel/stdlib/cwrapper/cwrapper.c
  pyccel/stdlib/cwrapper/cwrapper.h
  pyccel/stdlib/cwrapper/cwrapper_ndarrays.c
  pyccel/stdlib/cwrapper/cwrapper_ndarrays.h
Labels: Ready_to_merge

#958 Add support for type function
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/numpyext.py
  pyccel/codegen/compiling/compilers.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/codegen/utilities.py
  tests/epyccel/modules/generic_functions_2.py
  tests/epyccel/test_generic_functions.py
  tests/errors/semantic/blocking/COMPLEX_TYPE.py
  tests/pyccel/scripts/runtest_type_print.py
  tests/pyccel/test_pyccel.py
Labels: Ready_for_review

#971 [BUGFIX] Allow creation of array from matmul
  pyccel/ast/numpyext.py
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_bitwise.py
Labels: Ready_for_review, Ready_to_merge

#972 Bug fixes
  pyccel/codegen/printing/ccode.py
  pyccel/parser/semantic.py
  tests/epyccel/test_arrays_multiple_assignments.py
Labels: Ready_to_merge
