Repository pyccel/pyccel, pull requests merged in 2022-05, with the labels that each got.

#1103 Remove macOS warnings
  pyccel/codegen/compiling/compilers.py
Labels: needs_initial_review

#1104 Add missing error for wrong ordering
  pyccel/ast/core.py
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
  tests/internal/scripts/blas/ex2.py
  tests/internal/scripts/blas/ex3.py
  tests/internal/scripts/blas/ex4.py
  tests/internal/scripts/lapack/ex1.py
Labels: needs_initial_review

#993 Raise errors for stack arrays with invalid shapes
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
  tests/epyccel/test_arrays_multiple_assignments.py
  tutorial/decorators.md
Labels: Ready_for_review

#1109 Simplify `(x**2)**0.5` style expressions
  pyccel/ast/builtins.py
  pyccel/ast/class_defs.py
  pyccel/ast/numpyext.py
  pyccel/ast/operators.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/naming/fortrannameclashchecker.py
  pyccel/parser/semantic.py
  pyccel/version.py
  tests/epyccel/test_class_expressions.py
  tests/epyccel/test_epyccel_pow.py
Labels: Ready_to_merge

#1112 Allow use of argument for size of stack_array
  pyccel/parser/semantic.py
  tests/pyccel/scripts/runtest_degree_in.py
Labels: Ready_to_merge

#1113 Fix slow pyccel behaviour
  pyccel/ast/basic.py
  pyccel/ast/core.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  pyccel/version.py
Labels: needs_initial_review

#1116 Expose array module variables to Python - Fortran printer
  pyccel/ast/bind_c.py
  pyccel/ast/core.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
  pyccel/stdlib/cwrapper_ndarrays/cwrapper_ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.h
  tests/epyccel/modules/array_consts.py
  tests/epyccel/modules/awkward_names.py
  tests/epyccel/test_epyccel_modules.py
  tests/ndarrays/test_ndarrays.c
Labels: needs_initial_review
