Repository pyccel/pyccel, pull requests merged in 2022-11, with the labels that each got.

#1211 Use loop unrolling to handle NumpyArange
  pyccel/ast/numpyext.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
Labels: Ready_to_merge

#1221 Cuda grid implementation
  pyccel/ast/cudaext.py
  tests/internal/scripts/ccuda/cuda_grid.py
Labels: needs_initial_review, Language:Ccuda

#1202 Default to using Numpy precision in interfaces for arrays
  pyccel/ast/headers.py
  tests/epyccel/test_default_precision_template.py
Labels: Ready_to_merge

#1229 Enforce coverage
  .github/workflows/Github_pytest.yml
  .github/workflows/master.yml
  ci_tools/check_new_coverage.py
  ci_tools/coverage_analysis_tools.py
  ci_tools/git_evaluation_tools.py
Labels: Ready_to_merge

#1187 Fix arithmetic operations issues for Numpy arrays.
  pyccel/ast/internals.py
  pyccel/ast/operators.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/recognised_functions/test_numpy_types.py
  tests/epyccel/test_arrays.py
  tests/pyccel/scripts/array_binary_operation.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#1231 Add Missing temporary creation on return for C
  pyccel/codegen/printing/ccode.py
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_return_arrays.py
  tests/epyccel/test_return.py
Labels: Ready_to_merge

#1228 Addition of valid cudaMemcpyKind to cudaMemcpy
  pyccel/ast/cudaext.py
  pyccel/ast/cupyext.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccudacode.py
  pyccel/parser/semantic.py
Labels: needs_initial_review, Language:Ccuda

#1234 Auto-trigger benchmarks
  .github/workflows/bench.yml
  README.md
  ci_tools/check_new_coverage.py
  ci_tools/coverage_analysis_tools.py
  ci_tools/git_evaluation_tools.py
Labels: Ready_to_merge

#1239 Add integer min/max 2 argument functions to C
  ci_tools/coverage_analysis_tools.py
  pyccel/codegen/printing/ccode.py
  pyccel/version.py
  tests/epyccel/test_builtins.py
Labels: Ready_to_merge

#1237 Joss results
  joss-paper/paper.bib
  joss-paper/paper.md
  joss-paper/pypi_performance_310_1.7.0_compilation.pdf
  joss-paper/pypi_performance_310_1.7.0_execution.pdf
Labels: documentation

#1225 Add cuda.copy function
  pyccel/ast/cudaext.py
  pyccel/codegen/printing/ccudacode.py
  tests/internal/scripts/ccuda/cuda_copy.py
Labels: needs_initial_review, Language:Ccuda
