Repository pyccel/pyccel, pull requests merged in 2022-01, with the labels that each got.

#1058 In C files, never import inside a function
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
Labels: Ready_for_review

#1064 Update Python versions used in CI
  .github/workflows/Github_pytest.yml
  .github/workflows/master.yml
Labels: needs_initial_review

#1062 Allow tuple indexing of arrays
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/epyccel/test_tuples.py
Labels: needs_initial_review

#1055 Raise error for incorrect precision
  pyccel/parser/semantic.py
  tests/epyccel/modules/external_functions.py
  tests/epyccel/test_epyccel_functions.py
  tests/errors/semantic/non_blocking/INCOMPATIBLE_TYPES_IN_ASSIGNMENT_1.py
  tests/internal/scripts/mpi/reduce.py
Labels: Ready_to_merge

#1061 Automatic cast to booleans
  pyccel/codegen/printing/fcode.py
  tests/epyccel/modules/bitwise.py
  tests/epyccel/test_bitwise.py
Labels: Ready_to_merge

#1052 Return numpy scalar types
  pyccel/ast/bitwise_operators.py
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/datatypes.py
  pyccel/ast/internals.py
  pyccel/ast/literals.py
  pyccel/ast/macros.py
  pyccel/ast/mathext.py
  pyccel/ast/numpy_wrapper.py
  pyccel/ast/numpyext.py
  pyccel/ast/operators.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  pyccel/stdlib/cwrapper/cwrapper.c
  pyccel/stdlib/cwrapper/cwrapper.h
  tests/epyccel/modules/generic_functions_2.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_array_as_func_args.py
  tests/epyccel/test_epyccel_division.py
  tests/epyccel/test_epyccel_functions.py
  tests/epyccel/test_generic_functions.py
  tests/internal/scripts/mpi/reduce.py
  tests/pyccel/scripts/generic_functions.py
Labels: Ready_to_merge

#1060 Expose scalar module variables to Python (read-only) through getters
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/consts.py
  tests/epyccel/test_epyccel_modules.py
Labels: needs_initial_review

#1010 Cut long OpenMP pragmas in Fortran
  .github/actions/windows_install/action.yml
  pyccel/codegen/printing/fcode.py
  tests/epyccel/modules/openmp.py
  tests/epyccel/test_epyccel_openmp.py
  tests/pyccel/scripts/print_strings.py
Labels: Ready_to_merge
