Repository pyccel/pyccel, pull requests merged in 2022-06, with the labels that each got.

#1035 Benchmarks
  .github/workflows/Github_pytest.yml
  .github/workflows/bench.yml
  .gitignore
  README.md
  benchmarks/README.md
  benchmarks/code/ackermann_mod.py
  benchmarks/code/bellman_ford_mod.py
  benchmarks/code/dijkstra.py
  benchmarks/code/euler_mod.py
  benchmarks/code/laplace_2d_mod.py
  benchmarks/code/linearconv_1d_mod.py
  benchmarks/code/md_mod.py
  benchmarks/code/midpoint_explicit_mod.py
  benchmarks/code/midpoint_fixed_mod.py
  benchmarks/code/nonlinearconv_1d_mod.py
  benchmarks/code/numba_ackermann_mod.py
  benchmarks/code/numba_bellman_ford_mod.py
  benchmarks/code/numba_dijkstra.py
  benchmarks/code/numba_euler_mod.py
  benchmarks/code/numba_laplace_2d_mod.py
  benchmarks/code/numba_linearconv_1d_mod.py
  benchmarks/code/numba_md_mod.py
  benchmarks/code/numba_midpoint_explicit_mod.py
  benchmarks/code/numba_midpoint_fixed_mod.py
  benchmarks/code/numba_nonlinearconv_1d_mod.py
  benchmarks/code/numba_poisson_2d_mod.py
  benchmarks/code/numba_rk4_mod.py
  benchmarks/code/poisson_2d_mod.py
  benchmarks/code/rk4_mod.py
  benchmarks/run_benchmark.py
  performance.md
Labels: documentation, Ready_for_review

#1139 Fix Windows tests
  .github/actions/windows_install/action.yml
  .github/workflows/Github_pytest.yml
  README.md
  developer_docs/review_process.md
  pyccel/parser/parser.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#1132 Fix list comprehensions with anonymous iterators
  pyccel/ast/basic.py
  pyccel/codegen/printing/pycode.py
  pyccel/errors/messages.py
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/array_consts.py
  tests/epyccel/modules/functionals.py
  tests/epyccel/test_epyccel_modules.py
  tests/epyccel/test_functionals.py
Labels: Ready_to_merge

#1133 Memory flags handling
  .github/workflows/master.yml
  pyccel/ast/bind_c.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/headers.py
  pyccel/ast/numpy_wrapper.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntax/headers.py
Labels: Ready_to_merge

#1144 Fix Anaconda install on Windows
  .github/workflows/master.yml
Labels: Ready_to_merge

#858 Numpy where
  developer_docs/tips_and_tricks.md
  pyccel/ast/class_defs.py
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/errors/messages.py
  pyccel/naming/cnameclashchecker.py
  pyccel/naming/fortrannameclashchecker.py
  pyccel/parser/semantic.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/errors/semantic/blocking/NUMPY_WHERE_SINGLE_ARGUMENT.py
  tutorial/numpy-functions.md
Labels: Ready_for_review
