Repository pyccel/pyccel, pull requests merged in 2023-08, with the labels that each got.

#1475 [BOT] Don't cancel dependent jobs
  ci_tools/bot_clean_up.py
Labels: Ready_to_merge, Bot

#1473 Fix review status
  ci_tools/bot_clean_up.py
  ci_tools/bot_tools/github_api_interactions.py
Labels: Ready_to_merge, urgent, Bot

#1457 Improve class `ConstructorCall`
  CHANGELOG.md
  pyccel/ast/core.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
Labels: Ready_for_review, Classes

#1280 Fortran ordering, array of arrays, nested arrays
  AUTHORS
  CHANGELOG.md
  docs/numpy-functions.md
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/codegen/printing/ccode.py
  pyccel/naming/cnameclashchecker.py
  pyccel/stdlib/cwrapper_ndarrays/cwrapper_ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.h
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_epyccel_return_arrays.py
  tests/ndarrays/test_ndarrays.c
Labels: Ready_to_merge, urgent

#1478 Fix bot clean up
  .github/workflows/anaconda_linux.yml
  .github/workflows/anaconda_windows.yml
  ci_tools/bot_clean_up.py
  ci_tools/bot_comment_react.py
Labels: urgent, Bot

#1452 Add C support for a class containing only functions
  CHANGELOG.md
  pyccel/codegen/printing/ccode.py
  tests/pyccel/scripts/classes/classes_2_C.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge, Classes

#1483 [BOT] Fix docs for ci_tools
  .github/workflows/docs.yml
  ci_tools/bot_tools/bot_funcs.py
  ci_tools/coverage_analysis_tools.py
  ci_tools/list_docs_tovalidate.py
  ci_tools/process_results.py
Labels: Ready_to_merge, Bot

#1481 Fix anaconda_windows problems
  .github/workflows/anaconda_linux.yml
  .github/workflows/anaconda_windows.yml
Labels: Ready_to_merge, Bot

#1486 Fix uninitialised ndarray order
  pyccel/stdlib/cwrapper_ndarrays/cwrapper_ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.c
Labels: bug, Ready_to_merge

#1260 Clean PythonCodePrinter and add dtype property
  CHANGELOG.md
  ci_tools/json_pytest_output.py
  docs/numpy-functions.md
  pyccel/ast/class_defs.py
  pyccel/ast/cwrapper.py
  pyccel/ast/datatypes.py
  pyccel/ast/numpy_wrapper.py
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/recognised_functions/test_numpy_types.py
  tests/epyccel/test_arrays_multiple_assignments.py
Labels: Ready_to_merge

#1488 Add warnings to Type specification deprecations
  CHANGELOG.md
  docs/function-pointers-as-arguments.md
  docs/header-files.md
  docs/templates.md
  pyccel/decorators.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
Labels: Ready_to_merge, Type specification

#1477 C to Python wrapper rewrite
  CHANGELOG.md
  developer_docs/wrapper_stage.md
  pyccel/ast/bind_c.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/numpy_wrapper.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/python_wrapper.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/stdlib/cwrapper_ndarrays/cwrapper_ndarrays.c
  pyccel/stdlib/cwrapper_ndarrays/cwrapper_ndarrays.h
  pyccel/stdlib/ndarrays/ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.h
  pyccel/version.py
  tests/ndarrays/test_ndarrays.c
  tests/pyccel/test_pyccel.py
Labels: enhancement, internals, Ready_to_merge

#1502 Allowing the bot to re-run cancelled tests
  ci_tools/bot_tools/bot_funcs.py
Labels: Ready_to_merge, Bot

#1504 Fix review request
  ci_tools/bot_tools/github_api_interactions.py
Labels: Ready_to_merge, Bot

#1499 Fix passing temporary arrays to functions
  CHANGELOG.md
  pyccel/parser/semantic.py
  tests/pyccel/scripts/functions.py
  tests/pyccel/test_pyccel.py
Labels: bug, Ready_to_merge

#1256 Improve np.array implementation
  CHANGELOG.md
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_epyccel_return_arrays.py
Labels: bug, enhancement, Language:Fortran, Ready_to_merge

#1497 Add copy() method to ndarray
  CHANGELOG.md
  docs/numpy-functions.md
  pyccel/ast/class_defs.py
  pyccel/ast/core.py
  pyccel/ast/numpyext.py
  pyccel/parser/semantic.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: enhancement, Ready_to_merge

#1506 Fix none_dealloc bug
  .dict_custom.txt
  CHANGELOG.md
  pyccel/ast/cwrapper.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/version.py
Labels: Ready_to_merge
