Repository pyccel/pyccel, pull requests merged in 2023-11, with the labels that each got.

#1603 Fix fork PR commit check
  .github/actions/add_remote/action.yml
  .github/workflows/comment_bot.yml
  .github/workflows/prepare_review_stage.yml
  ci_tools/bot_comment_react.py
  ci_tools/bot_tools/bot_funcs.py
Labels: Ready_to_merge

#1589 Support call to built-in `tuple()`
  CHANGELOG.md
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  tests/epyccel/modules/tuples.py
  tests/epyccel/test_tuples.py
Labels: Ready_to_merge

#1596 Add preliminary wrapper for Python class
  CHANGELOG.md
  pyccel/ast/bind_c.py
  pyccel/ast/cwrapper.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/epyccel.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/epyccel/test_epyccel_classes.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge, Classes

#1591 Apply some Pylint fixes : Part 1
  .github/workflows/pylint.yml
  pyccel/ast/bitwise_operators.py
  pyccel/ast/class_defs.py
  pyccel/ast/operators.py
Labels: documentation, Ready_to_merge

#1592 Apply some Pylint fixes : Part 2
  .github/workflows/pylint.yml
  pyccel/ast/builtins.py
  pyccel/ast/numpyext.py
Labels: documentation, Ready_to_merge

#1598 Raise an error for ifs in comprehension statements
  CHANGELOG.md
  pyccel/parser/syntactic.py
Labels: documentation, Ready_to_merge

#1609 Apply some pylint fixes : part 3
  .github/workflows/pylint.yml
  CHANGELOG.md
  pyccel/ast/basic.py
  pyccel/ast/core.py
  pyccel/ast/utilities.py
  pyccel/errors/errors.py
  pyccel/parser/base.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/symbolic/__init__.py
  pyccel/symbolic/lambdify.py
Labels: Ready_to_merge

#1576 Ensure support for functions which pass and return classes
  CHANGELOG.md
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  tests/codegen/fcode/scripts/imports.py
  tests/errors/semantic/blocking/INTERFACE_CLASS__INIT__.py
  tests/errors/semantic/non_blocking/CLASS_ATTRIBUTE_REPEAT_ANNOTATION.py
  tests/pyccel/scripts/classes/classes_1.py
  tests/pyccel/scripts/classes/classes_3.py
  tests/pyccel/scripts/classes/classes_5.py
  tests/pyccel/scripts/classes/classes_6.py
  tests/pyccel/scripts/classes/classes_8.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge, Classes

#1625 Remove dead code
  CHANGELOG.md
  pyccel/parser/semantic.py
Labels: Ready_to_merge

#1590 Improve TypedAstNode to fully describe container types
  CHANGELOG.md
  pyccel/ast/basic.py
  pyccel/ast/bitwise_operators.py
  pyccel/ast/builtins.py
  pyccel/ast/c_concepts.py
  pyccel/ast/class_defs.py
  pyccel/ast/cmathext.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/datatypes.py
  pyccel/ast/functionalexpr.py
  pyccel/ast/internals.py
  pyccel/ast/literals.py
  pyccel/ast/macros.py
  pyccel/ast/mathext.py
  pyccel/ast/numpy_wrapper.py
  pyccel/ast/numpyext.py
  pyccel/ast/operators.py
  pyccel/ast/type_annotations.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  pyccel/utilities/metaclasses.py
  pyccel/utilities/stage.py
  tests/epyccel/recognised_functions/test_cmath_funcs.py
  tests/epyccel/recognised_functions/test_math_funcs.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_epyccel_IfTernaryOperator.py
  tests/errors/semantic/non_blocking/LIST_OF_TUPLES.py
Labels: internals, Ready_to_merge

#1627 Remove GCC intrinsics from Fortran printing of sign function
  CHANGELOG.md
  pyccel/codegen/printing/fcode.py
  pyccel/stdlib/numpy/numpy_f90.f90
Labels: Ready_to_merge

#1616 Add documentation for AST nodes
  .dict_custom.txt
  developer_docs/ast_nodes.md
  developer_docs/semantic_stage.md
Labels: documentation, Ready_to_merge

#1623 Remove HomogeneousTupleVariable
  CHANGELOG.md
  pyccel/ast/numpyext.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
Labels: Ready_to_merge

#1622 Fix builtins overriding imports
  CHANGELOG.md
  pyccel/parser/semantic.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Ready_to_merge

#1626 Make type annotation optional for `self` argument of bound methods
  CHANGELOG.md
  docs/classes.md
  pyccel/parser/syntactic.py
  tests/pyccel/scripts/classes/classes.py
  tests/pyccel/scripts/classes/classes_3.py
Labels: Ready_to_merge, Classes

#1617 Fix compiler configuration path resolution
  CHANGELOG.md
  pyccel/codegen/pipeline.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#1629 Handle scalar optionals as per the standard
  CHANGELOG.md
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/Module_4.py
  tests/epyccel/test_epyccel_augassign.py
  tests/epyccel/test_epyccel_mod.py
  tests/epyccel/test_epyccel_optional_args.py
Labels: Ready_to_merge

#1620 Handle class docstrings
  CHANGELOG.md
  pyccel/ast/bind_c.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/epyccel/test_docstrings.py
Labels: Ready_to_merge, Classes
