Repository pyccel/pyccel, pull requests merged in 2023-01, with the labels that each got.

#1277 Deactivate tests using deprecated numpy syntax
  .github/actions/pytest_run/action.yml
  .pylintrc
  ci_tools/coverage_analysis_tools.py
  pyccel/ast/builtins.py
  pyccel/codegen/utilities.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/recognised_functions/test_numpy_types.py
  tests/epyccel/test_generic_functions.py
  tests/pyccel/scripts/runtest_type_print.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge, urgent

#1283 Fix return Constants bug
  pyccel/parser/syntactic.py
  tests/epyccel/test_epyccel_functions.py
Labels: Ready_to_merge

#1286 Fix wrong interpretation of AugAssign to AliasAssign
  pyccel/parser/semantic.py
  tests/epyccel/modules/augassign.py
  tests/epyccel/test_epyccel_augassign.py
Labels: bug, Ready_to_merge

#1298 Improve CI
  .dict_custom.txt
  .github/workflows/Github_pytest.yml
  .github/workflows/lint.yml
  .github/workflows/pyccel_lint.yml
  .github/workflows/spelling.yml
  .pyspelling.yml
  README.md
  ci_tools/check_new_coverage.py
  ci_tools/check_slots.py
  ci_tools/coverage_analysis_tools.py
  ci_tools/git_evaluation_tools.py
  ci_tools/summarise_pyspelling.py
  developer_docs/how_to_solve_an_issue.md
  developer_docs/overview.md
  developer_docs/review_process.md
  developer_docs/scope.md
  pyccel/ast/basic.py
  pyccel/ast/bind_c.py
  pyccel/ast/bitwise_operators.py
  pyccel/ast/builtin_imports.py
  pyccel/ast/builtins.py
  pyccel/ast/c_concepts.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/datatypes.py
  pyccel/ast/headers.py
  pyccel/ast/internals.py
  pyccel/ast/itertoolsext.py
  pyccel/ast/literals.py
  pyccel/ast/numpyext.py
  pyccel/ast/omp.py
  pyccel/ast/operators.py
  pyccel/ast/scipyext.py
  pyccel/ast/sympy_helper.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  tutorial/builtin-functions.md
  tutorial/compiler.md
  tutorial/const_keyword.md
  tutorial/decorators.md
  tutorial/function-pointers-as-arguments.md
  tutorial/header-files.md
  tutorial/ndarrays.md
  tutorial/numpy-functions.md
  tutorial/openmp.md
  tutorial/quickstart.md
  tutorial/templates.md
Labels: Ready_to_merge

#1255 issue_1254 - Do not use exact comparison in tests involving floating …
  tests/epyccel/test_builtins.py
  tests/epyccel/test_epyccel_complex_func.py
  tests/epyccel/test_epyccel_functions.py
  tests/epyccel/test_epyccel_generators.py
  tests/epyccel/test_epyccel_optional_args.py
  tests/epyccel/test_generic_functions.py
Labels: Ready_to_merge

#1276 Add documentation for treatment of `order` in NumPy arrays
  .dict_custom.txt
  ci_tools/summarise_pyspelling.py
  developer_docs/order_docs.md
Labels: documentation, Ready_to_merge, good-first-issue

#1300 Fix type inference for Cupy array functions
  pyccel/ast/cupyext.py
  pyccel/parser/semantic.py
  tests/internal/scripts/ccuda/cupy_arange.py
  tests/internal/scripts/ccuda/cupy_array.py
Labels: needs_initial_review, Language:Ccuda

#1279 Fix kernel launch configuration errors
  pyccel/decorators.py
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
  tests/cuda_test/test_kernel_semantic.py
Labels: Ready_to_merge, Language:Ccuda

#1301 cleaning compile stage Cuda tests.
  pyccel/ast/core.py
  pyccel/ast/cudaext.py
  pyccel/ast/cupyext.py
  tests/internal/scripts/ccuda/cuda_array_device.py
  tests/internal/scripts/ccuda/cuda_array_host.py
  tests/internal/scripts/ccuda/cuda_array_managed.py
  tests/internal/scripts/ccuda/cuda_copy.py
  tests/internal/scripts/ccuda/cuda_grid.py
  tests/internal/scripts/ccuda/cupy_arange.py
  tests/internal/scripts/ccuda/cupy_array.py
  tests/internal/scripts/ccuda/kernel_launch.py
  tests/internal/scripts/ccuda/kernel_launch_config_literal.py
  tests/internal/scripts/ccuda/kernel_launch_config_variable.py
Labels: needs_initial_review, Language:Ccuda

#1291 Add coverage for cuda tests
  .github/actions/coverage_collection/action.yml
  .github/actions/coverage_install/action.yml
  .github/workflows/Cuda_pytest.yml
  .github/workflows/Github_pytest.yml
Labels: needs_initial_review

#1284 Add developer docs for the syntactic stage
  developer_docs/overview.md
  developer_docs/syntactic_stage.md
  pyccel/parser/syntactic.py
  pyccel/parser/syntax/headers.py
  tests/errors/syntax_errors/dict_str_keys.py
  tests/errors/syntax_errors/functions_in_template.py
  tests/errors/syntax_errors/functions_in_uniontype.py
  tests/errors/syntax_errors/import_star.py
  tests/errors/syntax_errors/nargs.py
  tests/errors/syntax_errors/not_implemented.py
Labels: documentation, Ready_to_merge

#1294 Add developer docs for the semantic stage
  .dict_custom.txt
  developer_docs/overview.md
  developer_docs/semantic_stage.md
  pyccel/parser/semantic.py
  tests/epyccel/modules/functionals.py
  tests/epyccel/test_functionals.py
  tutorial/builtin-functions.md
Labels: documentation, Ready_for_review

#1312 Use the same line endings throughout
  .gitattributes
  doc/make.bat
  obsolete/codegen/templates/cmake/FindSUITESPARSE.cmake
  pyccel/stdlib/ndarrays/ndarrays.c
  tests/epyccel/modules/Module_3.py
  tests/epyccel/modules/Module_4.py
  tests/epyccel/modules/Module_5.py
  tests/epyccel/modules/generic_functions_2.py
  tests/epyccel/modules/types.py
  tests/epyccel/test_epyccel_types.py
  tests/epyccel/test_imports.py
  tests/errors/semantic/blocking/INIT_NDARRAY_WITH_INHOMOG_LIST.py
  tests/ndarrays/conftest.py
Labels: Ready_to_merge

#1316 Always use LF line endings
  .gitattributes
Labels: Ready_to_merge

#1309 Add support for numpy.sum
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/stdlib/ndarrays/ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.h
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
Labels: Ready_to_merge

#1308 Fix compilation without static library
  pyccel/compilers/default_compilers.py
  pyccel/version.py
Labels: Ready_to_merge

#1319 Allow declaration of multiple np.linspace arrays in Fortran
  pyccel/codegen/printing/fcode.py
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
Labels: Ready_to_merge
