Repository pyccel/pyccel, pull requests merged in 2023-03, with the labels that each got.

#1326 Add developer docs for the codegen stage
  .dict_custom.txt
  .github/workflows/doc_coverage.yml
  .github/workflows/master.yml
  ci_tools/list_docs_tovalidate.py
  developer_docs/codegen_stage.md
  pyccel/codegen/compiling/compilers.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/modules/highorder_functions.py
  tests/epyccel/modules/tuples.py
  tests/epyccel/test_arrays_multiple_assignments.py
  tests/epyccel/test_class_expressions.py
  tests/epyccel/test_epyccel_functions.py
  tests/epyccel/test_higherorder_functions.py
Labels: documentation, needs_initial_review

#1278 Allow scalar/array template arguments
  pyccel/ast/builtins.py
  pyccel/ast/cwrapper.py
  pyccel/ast/numpy_wrapper.py
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/stdlib/cwrapper_ndarrays/cwrapper_ndarrays.c
  pyccel/stdlib/cwrapper_ndarrays/cwrapper_ndarrays.h
  tests/epyccel/modules/generic_functions_2.py
  tests/epyccel/test_generic_functions.py
Labels: needs_initial_review

#1338 Change byteflag definition to determine Interface
  pyccel/ast/cwrapper.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/version.py
Labels: Ready_for_review

#1341 minor changes in paper
  joss-paper/paper.md
Labels: Ready_to_merge

#1335 Save argument properties in argument object
  .pylintrc
  pyccel/ast/bind_c.py
  pyccel/ast/core.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
Labels: Ready_to_merge

#1345 Ensure cuda files are installed with pyccel
  .github/actions/pytest_run_cuda/action.yml
  .github/workflows/Github_pytest.yml
  MANIFEST.in
  pyproject.toml
  setup.cfg
Labels: Ready_for_review, Language:Ccuda
