Repository pyccel/pyccel, pull requests merged in 2023-05, with the labels that each got.

#1353 Add a FunctionDefResult object
  .github/workflows/doc_coverage.yml
  CHANGELOG.md
  ci_tools/bot_interaction.py
  ci_tools/coverage_analysis_tools.py
  ci_tools/summarise_doccoverage.py
  pyccel/ast/bind_c.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/headers.py
  pyccel/ast/numpy_wrapper.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
Labels: Ready_to_merge

#1374 Fix installation instructions
  AUTHORS
  README.md
  ci_tools/bot_interaction.py
Labels: Ready_to_merge

#1380 Ensure temporary arrays created for function calls are correctly declared in loops.
  CHANGELOG.md
  pyccel/parser/semantic.py
  pyccel/version.py
  tests/epyccel/modules/loops.py
  tests/epyccel/test_loops.py
Labels: Ready_to_merge

#1386 Rename master -> devel in workflow files
  .github/workflows/Github_pytest.yml
  .github/workflows/bench.yml
  .github/workflows/devel.yml
Labels: Ready_to_merge

#1395 Enforce checklist completion
  ci_tools/bot_interaction.py
  ci_tools/bot_messages/checklist.txt
  ci_tools/bot_messages/set_draft_checklist_incomplete.txt
  ci_tools/git_evaluation_tools.py
Labels: Ready_to_merge, urgent

#1393 Raise error message when parsing empty class
  AUTHORS
  CHANGELOG.md
  pyccel/errors/messages.py
  pyccel/parser/syntactic.py
  tests/errors/syntax_errors/empty_class.py
Labels: Ready_to_merge

#1385 Remove unnecessary settings argument from SemanticParser
  AUTHORS
  CHANGELOG.md
  developer_docs/semantic_stage.md
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
Labels: Ready_to_merge

#1406 Fix bug in documentation checker
  ci_tools/list_docs_tovalidate.py
Labels: Ready_for_review, urgent

#1388 Rewrite bind C wrapper
  .pylintrc
  CHANGELOG.md
  ci_tools/list_docs_tovalidate.py
  developer_docs/overview.md
  developer_docs/wrapper_stage.md
  obsolete/parser/syntax/himi.py
  obsolete/tests/test_himi.py
  pyccel/ast/bind_c.py
  pyccel/ast/core.py
  pyccel/ast/datatypes.py
  pyccel/ast/numpy_wrapper.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/python_wrapper.py
  pyccel/codegen/wrapper/__init__.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/codegen/wrapper/wrapper.py
  pyccel/compilers/default_compilers.py
  pyccel/naming/cnameclashchecker.py
  pyccel/naming/fortrannameclashchecker.py
  pyccel/naming/languagenameclashchecker.py
  pyccel/naming/pythonnameclashchecker.py
  pyccel/parser/scope.py
  pyccel/stdlib/cwrapper_ndarrays/cwrapper_ndarrays.c
  pyccel/stdlib/cwrapper_ndarrays/cwrapper_ndarrays.h
  pyccel/utilities/metaclasses.py
  pyccel/utilities/strings.py
  tests/epyccel/test_arrays.py
Labels: Ready_to_merge
