Repository pyccel/pyccel, pull requests merged in 2023-04, with the labels that each got.

#1328 Fix allocation mishandling in CUDA array creation
  .github/actions/pytest_run/action.yml
  .github/actions/pytest_run_cuda/action.yml
  .github/actions/pytest_run_python/action.yml
  pyccel/stdlib/cuda_ndarrays/cuda_ndarrays.cu
  tests/cuda_ndarrays/conftest.py
  tests/cuda_ndarrays/test_cuda_ndarrays.cu
Labels: Ready_to_merge, Language:Ccuda

#1360 Minor bot fixes
  .github/workflows/Github_pytest.yml
  .github/workflows/anaconda_linux.yml
  .github/workflows/anaconda_windows.yml
  .github/workflows/coverage.yml
  .github/workflows/doc_coverage.yml
  .github/workflows/lint.yml
  .github/workflows/linux.yml
  .github/workflows/macosx.yml
  .github/workflows/pickle.yml
  .github/workflows/pickle_wheel.yml
  .github/workflows/pyccel_lint.yml
  .github/workflows/spelling.yml
  .github/workflows/windows.yml
  ci_tools/bot_interaction.py
  ci_tools/bot_messages/show_tests.txt
  ci_tools/bot_messages/untrusted_user.txt
  ci_tools/check_new_coverage.py
  ci_tools/git_evaluation_tools.py
Labels: Ready_to_merge

#1362 Link Python dynamically for smaller extension modules
  CHANGELOG.md
  pyccel/compilers/default_compilers.py
Labels: Ready_to_merge

#1364 Cleanup builtin_import_registery
  pyccel/ast/utilities.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
Labels: Ready_to_merge

#1363 Fix minor bot issues
  .github/workflows/Github_pytest.yml
  .github/workflows/coverage.yml
  .github/workflows/pyccel_lint.yml
  .github/workflows/review_bot.yml
  ci_tools/bot_interaction.py
  ci_tools/bot_messages/bot_commands.txt
  ci_tools/bot_messages/show_tests.txt
Labels: Ready_to_merge

#1369 Improve coverage check
  .github/ISSUE_TEMPLATE/coverage.md
  ci_tools/bot_interaction.py
  ci_tools/bot_messages/bot_commands.txt
  ci_tools/bot_messages/coverage_ignored.txt
  ci_tools/bot_messages/warn_coverage.txt
  ci_tools/check_new_coverage.py
  ci_tools/check_pylint_commands.py
  ci_tools/coverage_analysis_tools.py
  developer_docs/review_process.md
Labels: Ready_to_merge, urgent

#1367 Fix linking error with Anaconda
  CHANGELOG.md
  ci_tools/list_docs_tovalidate.py
  pyccel/codegen/compiling/basic.py
  pyccel/codegen/python_wrapper.py
  pyccel/compilers/default_compilers.py
Labels: Ready_to_merge
