Repository pyccel/pyccel, pull requests merged in 2023-02, with the labels that each got.

#1299 Fix array slicing
  pyccel/ast/internals.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/pycode.py
  pyccel/stdlib/ndarrays/ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.h
  pyccel/version.py
  tests/ndarrays/test_ndarrays.c
  tests/pyccel/scripts/arrays_view.py
  tests/pyccel/test_pyccel.py
Labels: bug, Language:C, needs_initial_review

#1292 Adding git actions for automating documentation validation and coverage
  .github/workflows/doc_coverage.yml
  ci_tools/list_docs_tovalidate.py
  ci_tools/summarise_doccoverage.py
Labels: documentation, Ready_to_merge

#1324 Clean up Doc Coverage action
  .github/workflows/doc_coverage.yml
  ci_tools/list_docs_tovalidate.py
  ci_tools/process_results.py
  developer_docs/review_process.md
Labels: documentation, Ready_to_merge

#1325 Ignore certain objects at numpydoc validation
  ci_tools/list_docs_tovalidate.py
  ci_tools/process_results.py
Labels: Ready_to_merge
