Repository pyccel/pyccel, pull requests merged in 2023-10, with the labels that each got.

#1525 Cleanup some datatype handling
  CHANGELOG.md
  pyccel/ast/builtins.py
  pyccel/ast/cwrapper.py
  pyccel/ast/datatypes.py
  pyccel/ast/headers.py
  pyccel/ast/internals.py
  pyccel/ast/numpyext.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntax/headers.py
Labels: Ready_to_merge

#1524 Change default type handling behaviour - Part 1
  .dict_custom.txt
  CHANGELOG.md
  README.md
  ci_tools/bot_tools/bot_funcs.py
  developer_docs/type_inference.md
  pyccel/ast/headers.py
  pyccel/ast/internals.py
  pyccel/ast/type_annotations.py
  pyccel/ast/variable.py
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/parser/syntax/headers.py
  tests/epyccel/test_epyccel_headers.py
Labels: Ready_to_merge

#1537 Fix Variable.clone function
  pyccel/ast/variable.py
Labels: Ready_to_merge

#1542 Fix homepage badges
  .github/workflows/anaconda_linux.yml
  .github/workflows/anaconda_windows.yml
  .github/workflows/coverage.yml
  .github/workflows/devel.yml
  .github/workflows/docs.yml
  .github/workflows/linux.yml
  .github/workflows/macosx.yml
  .github/workflows/pickle.yml
  .github/workflows/pickle_wheel.yml
  .github/workflows/pyccel_lint.yml
  .github/workflows/pylint.yml
  .github/workflows/spelling.yml
  .github/workflows/windows.yml
  README.md
  ci_tools/setup_check_run.py
Labels: Ready_to_merge

#1546 Bot bug fixes for collaborators on forks
  ci_tools/bot_comment_react.py
  ci_tools/bot_tools/bot_funcs.py
  ci_tools/bot_tools/github_api_interactions.py
Labels: Ready_to_merge, urgent, Bot

#1549 Don't auto-create checklists to fix fork problems
  ci_tools/bot_comment_react.py
  ci_tools/bot_hello.py
  ci_tools/bot_messages/checklist.txt
  ci_tools/bot_messages/first_checklist.txt
  ci_tools/bot_messages/missing_checklist.txt
  ci_tools/bot_messages/welcome_friend.txt
  ci_tools/bot_messages/welcome_newcomer.txt
  ci_tools/bot_tools/bot_funcs.py
  ci_tools/bot_tools/github_api_interactions.py
Labels: bug, Ready_to_merge, urgent, Bot

#1535 Clean up backtrace error
  .dict_custom.txt
  CHANGELOG.md
  pyccel/ast/builtins.py
  tests/errors/semantic/blocking/TUPLE_WITH_INCOHERENT_RANKS.py
Labels: Ready_to_merge

#1547 Add Intel tests to devel branch
  .github/actions/intel_install/action.yml
  .github/workflows/intel.yml
  CHANGELOG.md
  ci_tools/bot_messages/show_tests.txt
  ci_tools/bot_tools/bot_funcs.py
  ci_tools/devel_branch_tests.py
  docs/compiler.md
  pyccel/codegen/pipeline.py
  pyccel/compilers/default_compilers.py
  tests/epyccel/recognised_functions/test_cmath_funcs.py
  tests/epyccel/recognised_functions/test_math_funcs.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_epyccel_openmp.py
Labels: Ready_to_merge

#1550 Fix minor bugs
  .github/workflows/intel.yml
  README.md
  ci_tools/bot_tools/bot_funcs.py
Labels: Ready_to_merge

#1508 Add C support for a class destructor
  .dict_custom.txt
  CHANGELOG.md
  pyccel/ast/core.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  pyccel/version.py
  tests/codegen/fcode/scripts/imports.py
  tests/pyccel/scripts/classes/classes_2.py
  tests/pyccel/scripts/classes/classes_4.py
  tests/pyccel/scripts/classes/classes_6.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge, Classes

#1512 Remove Python 3.7 support
  CHANGELOG.md
  ci_tools/bot_tools/bot_funcs.py
  ci_tools/devel_branch_tests.py
  setup.cfg
Labels: Ready_to_merge

#1557 Return instance of user class. Reuse variable for multiple instances
  CHANGELOG.md
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/pyccel/scripts/classes/classes_1.py
  tests/pyccel/scripts/classes/classes_3.py
  tests/pyccel/scripts/classes/classes_7.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge, Classes

#1563 Fix coverage trigger
  ci_tools/bot_tools/bot_funcs.py
Labels: Ready_to_merge, urgent, Bot

#1558 Add commas to format specifiers
  CHANGELOG.md
  ci_tools/bot_messages/show_tests.txt
  pyccel/codegen/printing/fcode.py
Labels: Ready_to_merge

#1573 Fix Windows runner
  .github/actions/windows_install/action.yml
Labels: Ready_to_merge, urgent

#1523 Change default type handling behaviour
  .dict_custom.txt
  .pylintrc
  CHANGELOG.md
  developer_docs/type_inference.md
  docs/quickstart.md
  pyccel/ast/basic.py
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/headers.py
  pyccel/ast/internals.py
  pyccel/ast/literals.py
  pyccel/ast/type_annotations.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/errors/errors.py
  pyccel/errors/messages.py
  pyccel/parser/grammar/headers.tx
  pyccel/parser/grammar/types.tx
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/parser/syntax/headers.py
  pyccel/stdlib/external/mpi4py.py
  pyccel/stdlib/internal/lapack.pyh
  tests/codegen/fcode/scripts/precision.py
  tests/epyccel/modules/generic_functions.py
  tests/epyccel/modules/generic_functions_2.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_array_as_func_args.py
  tests/epyccel/test_class_expressions.py
  tests/epyccel/test_epyccel_functions.py
  tests/epyccel/test_epyccel_headers.py
  tests/errors/semantic/blocking/INTERFACE_WRONG_TYPES.py
  tests/errors/semantic/non_blocking/UNION_RETURN_TYPE.py
  tests/errors/semantic/non_blocking/UNION_RETURN_TYPE_headers.py
  tests/errors/semantic/non_blocking/UNION_RETURN_TYPE_types.py
  tests/errors/semantic/non_blocking/functions_in_uniontype.py
  tests/errors/syntax_errors/DECORATOR_WRONG_NUMBER_TYPES.py
  tests/errors/syntax_errors/HEADER_WRONG_NUMBER_TYPES.py
  tests/pyccel/scripts/classes/class_headers.py
  tests/pyccel/scripts/default_args_mod.py
  tests/pyccel/scripts/functions.py
  tests/pyccel/scripts/generic_functions.py
  tests/pyccel/scripts/runtest_default_args.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#1574 Add type annotations for variable
  CHANGELOG.md
  docs/templates.md
  docs/type_annotations.md
  pyccel/ast/core.py
  pyccel/ast/internals.py
  pyccel/ast/type_annotations.py
  pyccel/ast/variable.py
  pyccel/errors/messages.py
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/parser/syntax/headers.py
  pyccel/version.py
  tests/epyccel/test_epyccel_headers.py
  tests/epyccel/test_epyccel_variable_annotations.py
  tests/errors/semantic/non_blocking/CONST_ASSIGNED_ARGUMENT.py
  tests/errors/semantic/non_blocking/CONST_ASSIGNED_ARGUMENT2.py
  tests/errors/semantic/non_blocking/REPEAT_ANNOTATION.py
  tests/errors/semantic/non_blocking/pep526.py
  tests/errors/semantic/non_blocking/wrong_class_type_annotation.py
  tests/errors/syntax_errors/CLASS_VARIABLES.py
  tests/pyccel/scripts/classes/class_variables.py
  tests/pyccel/scripts/classes/pep526.py
  tests/pyccel/test_pyccel.py
  tests/syntax/scripts/classes.py
Labels: Ready_to_merge

#1579 Update CHANGELOG.md
  CHANGELOG.md
Labels: Ready_to_merge

#1584 Remove dead code
  CHANGELOG.md
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/datatypes.py
  pyccel/ast/headers.py
  pyccel/ast/numpyext.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/base.py
  pyccel/parser/syntax/headers.py
Labels: Ready_to_merge

#1580 Add documentation for classes.
  .dict_custom.txt
  CHANGELOG.md
  docs/classes.md
Labels: documentation, Ready_to_merge, Classes

#1588 Fix unnecessarily long epyccel file names
  CHANGELOG.md
  pyccel/epyccel.py
Labels: Ready_to_merge
