Repository pyccel/pyccel, pull requests merged in 2023-07, with the labels that each got.

#1428 Fix AugAssign with templates and literal rhs
  .dict_custom.txt
  CHANGELOG.md
  pyccel/ast/basic.py
  pyccel/parser/semantic.py
  pyccel/utilities/stage.py
  tests/epyccel/modules/generic_functions_2.py
  tests/epyccel/test_generic_functions.py
Labels: Ready_to_merge

#1432 Add conjugate methods for ints and floats
  CHANGELOG.md
  pyccel/ast/builtins.py
  pyccel/ast/class_defs.py
  pyccel/version.py
  tests/epyccel/test_class_expressions.py
Labels: Ready_to_merge

#1433 Update CHANGELOG.md
  CHANGELOG.md
Labels: Ready_to_merge

#1445 Fix race condition
  .github/actions/pytest_run/action.yml
  CHANGELOG.md
  pyccel/codegen/compiling/basic.py
  pyccel/codegen/compiling/compilers.py
  pyccel/codegen/utilities.py
  tests/conftest.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Ready_to_merge

#1446 Adding Python support for a simple class
  CHANGELOG.md
  pyccel/codegen/printing/pycode.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#1431 Fix generic methods in classes
  .dict_custom.txt
  CHANGELOG.md
  pyccel/ast/class_defs.py
  pyccel/ast/core.py
  pyccel/ast/datatypes.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/codegen/fcode/scripts/concatenation.py
  tests/epyccel/test_class_expressions.py
  tests/errors/known_bugs/context.py
  tests/errors/semantic/blocking/unknown_method.py
  tests/errors/semantic/non_blocking/class_inheritance.py
  tests/errors/test_errors.py
  tests/pyccel/scripts/classes/classes_5.py
  tests/pyccel/scripts/classes/generic_methods.py
  tests/pyccel/scripts/concatenation.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge, urgent

#1451 Rename `__pyccel__` and `__epyccel__` folders
  .github/workflows/review_bot.yml
  CHANGELOG.md
  ci_tools/bot_comment_react.py
  ci_tools/bot_ready_for_review.py
  ci_tools/bot_tools/bot_funcs.py
  ci_tools/process_results.py
  ci_tools/summarise_pyspelling.py
  docs/compiler.md
  docs/quickstart.md
  pyccel/codegen/pipeline.py
  pyccel/commands/pyccel_clean.py
  pyccel/epyccel.py
  tests/epyccel/test_epyccel_functions.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#1447 Minor developer doc improvement
  .github/workflows/docs.yml
  developer_docs/codegen_stage.md
  developer_docs/semantic_stage.md
  developer_docs/syntactic_stage.md
Labels: documentation, Ready_for_review

#1463 Fix docs setup
  .github/workflows/docs.yml
  .github/workflows/pyccel_lint.yml
  ci_tools/bot_tools/bot_funcs.py
  ci_tools/devel_branch_tests.py
Labels: Ready_to_merge, urgent, Bot

#1464 [BOT] Always post run duration
  ci_tools/bot_tools/bot_funcs.py
  ci_tools/bot_tools/github_api_interactions.py
Labels: Ready_to_merge, Bot

#1454 Fix non-fatal developer-mode output
  .github/workflows/docs.yml
  CHANGELOG.md
  ci_tools/process_results.py
  pyccel/codegen/pipeline.py
  pyccel/errors/errors.py
  tests/errors/test_errors.py
Labels: Ready_to_merge, Bot

#1466 Bot fixes
  ci_tools/bot_tools/bot_funcs.py
  ci_tools/summarise_doccoverage.py
Labels: Ready_to_merge, Bot
