Repository pyccel/pyccel, pull requests merged in 2024-02, with the labels that each got.

#1713 Get actual Homebrew directory with `brew --prefix`
  CHANGELOG.md
  pyccel/compilers/default_compilers.py
Labels: Ready_to_merge

#1686 Fix target/pointer issues with classes
  .dict_custom.txt
  CHANGELOG.md
  developer_docs/semantic_stage.md
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/parser/base.py
  pyccel/parser/semantic.py
  tests/codegen/fcode/scripts/classes_2.py
  tests/epyccel/test_epyccel_classes.py
  tests/errors/semantic/non_blocking/class_target_redefinition.py
  tests/errors/semantic/non_blocking/class_target_scoping.py
  tests/errors/semantic/non_blocking/pointer_to_temporary.py
  tests/pyccel/scripts/classes/class_pointer.py
  tests/pyccel/scripts/classes/class_temporary_in_constructor.py
  tests/pyccel/scripts/classes/class_with_non_target_array_arg.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge, Classes

#1711 Add timers and fix set usage
  CHANGELOG.md
  pyccel/codegen/pipeline.py
  pyccel/codegen/python_wrapper.py
  pyccel/commands/console.py
  pyccel/epyccel.py
  pyccel/naming/cnameclashchecker.py
  pyccel/naming/fortrannameclashchecker.py
  pyccel/naming/languagenameclashchecker.py
  pyccel/naming/pythonnameclashchecker.py
  pyccel/parser/semantic.py
  tests/pyccel/test_pyccel.py
Labels: enhancement, Ready_to_merge

#1707 Allow class usage in a project
  .dict_custom.txt
  .github/actions/pytest_run/action.yml
  CHANGELOG.md
  ci_tools/check_pylint_commands.py
  developer_docs/wrapper_stage.md
  pyccel/ast/c_concepts.py
  pyccel/ast/class_defs.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/numpy_wrapper.py
  pyccel/codegen/codegen.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/python_wrapper.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/epyccel.py
  pyccel/errors/errors.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/pyccel/project_class_imports/project/__init__.py
  tests/pyccel/project_class_imports/project/basics/Line_mod.py
  tests/pyccel/project_class_imports/project/basics/Point_mod.py
  tests/pyccel/project_class_imports/project/basics/__init__.py
  tests/pyccel/project_class_imports/project/shapes/Square_mod.py
  tests/pyccel/project_class_imports/project/shapes/__init__.py
  tests/pyccel/project_class_imports/runtest.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge, Classes, next release

#1717 Fix: handle paths with dots
  CHANGELOG.md
  pyccel/parser/base.py
Labels: bug, Ready_to_merge, next release

#1718 Minor bot fixes
  ci_tools/bot_tools/bot_funcs.py
Labels: Ready_to_merge, urgent, Bot

#1715 Allow returning pointers which point to arguments
  CHANGELOG.md
  developer_docs/wrapper_stage.md
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/numpy_wrapper.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
  tests/epyccel/classes/classes_1.py
  tests/epyccel/classes/return_class_pointer.py
  tests/epyccel/classes/return_unknown_class_pointer.py
  tests/epyccel/modules/return_pointers.py
  tests/epyccel/test_epyccel_classes.py
  tests/epyccel/test_epyccel_garbage_collection.py
  tests/epyccel/test_pointers.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge, next release

#1706 Wrap class variables
  CHANGELOG.md
  docs/classes.md
  pyccel/ast/bind_c.py
  pyccel/ast/cwrapper.py
  pyccel/ast/numpy_wrapper.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/parser/semantic.py
  pyccel/version.py
  tests/epyccel/classes/array_attribute.py
  tests/epyccel/classes/ptr_in_class.py
  tests/epyccel/test_epyccel_classes.py
  tests/epyccel/test_epyccel_garbage_collection.py
  tests/epyccel/test_epyccel_return_arrays.py
Labels: Ready_to_merge, Classes, next release

#1725 Minor bot fix
  ci_tools/bot_tools/bot_funcs.py
Labels: Ready_to_merge, urgent, Bot

#1724 Fix returns in for loops
  CHANGELOG.md
  pyccel/parser/semantic.py
  pyccel/version.py
  tests/epyccel/modules/loops.py
  tests/epyccel/test_loops.py
Labels: bug, Ready_to_merge

#1726 Fix Pyccel checks
  CHANGELOG.md
  ci_tools/check_slots.py
Labels: Ready_to_merge, urgent, Bot

#1709 List support: append method
  CHANGELOG.md
  pyccel/ast/builtin_methods/list_methods.py
  pyccel/ast/class_defs.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_lists.py
  tests/errors/semantic/blocking/APPEND_LIST_INCOMPATIBLE_TYPES_0.py
  tests/errors/semantic/blocking/APPEND_LIST_INCOMPATIBLE_TYPES_1.py
  tests/errors/semantic/blocking/APPEND_LIST_INCOMPATIBLE_TYPES_2.py
  tests/errors/semantic/blocking/APPEND_LIST_INCOMPATIBLE_TYPES_4.py
Labels: Feature, Ready_to_merge, Containers

#1575 Variable type annotations for homogeneous tuples
  CHANGELOG.md
  docs/type_annotations.md
  pyccel/ast/builtins.py
  pyccel/ast/class_defs.py
  pyccel/ast/core.py
  pyccel/ast/literals.py
  pyccel/ast/numpyext.py
  pyccel/parser/grammar/types.tx
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/parser/syntax/headers.py
  tests/epyccel/modules/highorder_functions.py
  tests/epyccel/modules/tuples.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_epyccel_variable_annotations.py
  tests/errors/semantic/non_blocking/INCOMPATIBLE_TYPES_IN_ASSIGNMENT_4.py
  tests/errors/semantic/non_blocking/INCOMPATIBLE_TYPES_IN_ASSIGNMENT_5.py
Labels: Ready_to_merge, Type specification, Containers

#1730 Remove unnecessary dtype property from Declare
  CHANGELOG.md
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  tests/warnings/test_warnings.py
Labels: internals, Ready_to_merge

#1710 List support: pop method
  AUTHORS
  CHANGELOG.md
  pyccel/ast/builtin_methods/list_methods.py
  pyccel/ast/class_defs.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/test_epyccel_lists.py
Labels: Feature, Ready_to_merge, Containers

#1733 Minor bot fix
  ci_tools/bot_tools/bot_funcs.py
Labels: Ready_to_merge, urgent, Bot

#1734 List support: clear method
  CHANGELOG.md
  pyccel/ast/builtin_methods/list_methods.py
  pyccel/ast/class_defs.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/test_epyccel_lists.py
Labels: Feature, Ready_to_merge, Containers

#1552 Support NumPy functions `isnan`, `isinf`, `isfinite`
  CHANGELOG.md
  docs/numpy-functions.md
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Ready_for_review

#1727 List support/insert method
  CHANGELOG.md
  pyccel/ast/builtin_methods/list_methods.py
  pyccel/ast/class_defs.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/modules/list_user_defined_objs.py
  tests/epyccel/test_epyccel_lists.py
  tests/errors/semantic/blocking/INSERT_LIST_INCOMPATIBLE_TYPES_0.py
  tests/errors/semantic/blocking/INSERT_LIST_INCOMPATIBLE_TYPES_1.py
  tests/errors/semantic/blocking/INSERT_LIST_INCOMPATIBLE_TYPES_2.py
  tests/errors/semantic/blocking/INSERT_LIST_INCOMPATIBLE_TYPES_3.py
Labels: Feature, Ready_to_merge, Containers

#1761 Remove dead code
  pyccel/ast/builtins.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/test_builtins.py
Labels: internals, Ready_to_merge
