Repository pyccel/pyccel, pull requests merged in 2024-05, with the labels that each got.

#1843 Set support: `update` method
  CHANGELOG.md
  pyccel/ast/builtin_methods/list_methods.py
  pyccel/ast/builtin_methods/set_methods.py
  pyccel/ast/class_defs.py
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_sets.py
  tests/errors/semantic/blocking/UPDATE_SET_INCOMPATIBLE_TYPES_1.py
  tests/errors/semantic/blocking/UPDATE_SET_INCOMPATIBLE_TYPES_2.py
Labels: Ready_to_merge

#1854 Fix translation for conflicting module name
  CHANGELOG.md
  pyccel/ast/core.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/codeprinter.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/codegen/python_wrapper.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/pyccel/scripts/endif.py
  tests/pyccel/scripts/runtest_badly_named_module.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge, next release

#1860 Ensure workflows run on main branch
  .github/workflows/anaconda_linux.yml
  .github/workflows/anaconda_windows.yml
  .github/workflows/intel.yml
  .github/workflows/linux.yml
  .github/workflows/macosx.yml
  .github/workflows/pickle.yml
  .github/workflows/pickle_wheel.yml
  .github/workflows/windows.yml
Labels: Ready_to_merge, next release

#1865 Fix comment bot
  ci_tools/bot_tools/github_api_interactions.py
Labels: bug, Ready_to_merge, urgent, Bot

#1866 Raise an error for issue #1339
  CHANGELOG.md
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  tests/errors/codegen/fortran_blocking/FORTRAN_ALLOCATABLE_IN_EXPRESSION.py
  tests/errors/codegen/fortran_blocking/randint.py
  tests/errors/codegen/fortran_non_blocking/issue_1339.py
  tests/errors/test_errors.py
Labels: Ready_to_merge

#1870 Fix Wrapper Documentation.
  developer_docs/wrapper_stage.md
Labels: documentation, Ready_to_merge

#1869 Hide traceback for epyccel and lambdify errors
  CHANGELOG.md
  pyccel/commands/epyccel.py
  pyccel/commands/lambdify.py
Labels: Ready_to_merge, next release

#1859 Update version and CHANGELOG for v1.12.0
  CHANGELOG.md
  pyccel/version.py
Labels: Ready_to_merge, next release

#1120 improved print_constant
  CHANGELOG.md
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  tests/pyccel/scripts/print_nan.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#1873 Update deprecated action (4 lines)
  .github/workflows/anaconda_linux.yml
  .github/workflows/intel.yml
  .github/workflows/linux.yml
Labels: Ready_to_merge

#1904 Store annotated local variables to avoid memory leaks
  CHANGELOG.md
  pyccel/parser/semantic.py
  tests/ndarrays/leaks_check.py
Labels: bug, Language:C, Ready_to_merge, urgent
