Repository pyccel/pyccel, pull requests merged in 2024-08, with the labels that each got.

#1906 Add support for type aliases
  .pylintrc
  CHANGELOG.md
  docs/type_annotations.md
  pyccel/ast/class_defs.py
  pyccel/ast/datatypes.py
  pyccel/ast/typingext.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/epyccel/modules/Module_10.py
  tests/epyccel/modules/Module_9.py
  tests/epyccel/test_epyccel_modules.py
  tests/errors/semantic/blocking/TYPE_ALIAS_REASSIGN.py
  tests/errors/semantic/blocking/UNANNOTATED_TYPE_ALIAS.py
  tests/errors/semantic/non_blocking/wrong_class_type_annotation.py
Labels: Ready_for_review

#1898 fixed list function implementation
  AUTHORS
  CHANGELOG.md
  pyccel/ast/builtins.py
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_lists.py
Labels: Ready_to_merge

#1958 Fix usage of used_names in pyccel_to_sympy
  CHANGELOG.md
  pyccel/ast/sympy_helper.py
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/functionals.py
  tests/epyccel/modules/tuples.py
  tests/epyccel/test_functionals.py
Labels: Ready_for_review

#1965 Fix minor bot bug
  ci_tools/bot_tools/bot_funcs.py
Labels: Ready_for_review, urgent, Bot

#1964 Raise NumPy wrong argument error details
  CHANGELOG.md
  pyccel/ast/numpy_wrapper.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/stdlib/cwrapper_ndarrays/cwrapper_ndarrays.c
  pyccel/stdlib/cwrapper_ndarrays/cwrapper_ndarrays.h
Labels: Ready_for_review

#1838 Remove InhomogeneousTupleVariable
  CHANGELOG.md
  developer_docs/tuples.md
  docs/containers.md
  docs/type_annotations.md
  pyccel/ast/builtins.py
  pyccel/ast/numpyext.py
  pyccel/ast/operators.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/tuples.py
  tests/errors/semantic/blocking/LIST_OF_TUPLES.py
  tests/pyccel/scripts/classes/tuples_in_classes.py
  tests/pyccel/test_pyccel.py
Labels: Ready_for_review, Type specification, Containers
