Repository pyccel/pyccel, pull requests merged in 2024-11, with the labels that each got.

#2032 Add missing dependency to installation description
  docs/installation.md
Labels: Ready_for_review

#2034 Remove unnecessary set class (pyccel #2018)
  AUTHORS
  pyccel/ast/builtin_methods/set_methods.py
  pyccel/ast/class_defs.py
Labels: Ready_to_merge

#2037 Fix reoccurring overflow errors
  tests/epyccel/recognised_functions/test_numpy_types.py
  tests/epyccel/test_builtins.py
Labels: Ready_for_review

#2038 Fix pointer assignment for list/set/dict
  CHANGELOG.md
  pyccel/ast/builtins.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_dicts.py
  tests/epyccel/test_epyccel_lists.py
  tests/epyccel/test_epyccel_sets.py
Labels: Ready_for_review

#2033 #1888: add setdefault classes for dict
  AUTHORS
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/builtin_methods/dict_methods.py
  pyccel/ast/class_defs.py
  tests/epyccel/test_epyccel_dicts.py
Labels: needs_initial_review

#2030 Allow iterating over a set
  CHANGELOG.md
  pyccel/ast/builtins.py
  pyccel/ast/low_level_tools.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/test_epyccel_sets.py
Labels: Ready_for_review

#2029 [DICT] Add Python support for clear
  AUTHORS
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/builtin_methods/dict_methods.py
  pyccel/ast/class_defs.py
  tests/epyccel/test_epyccel_dicts.py
Labels: Ready_to_merge

#2044 Add Python support for dict.copy
  AUTHORS
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/builtin_methods/dict_methods.py
  pyccel/ast/class_defs.py
  tests/epyccel/test_epyccel_dicts.py
Labels: needs_initial_review

#2040 Fix use of `_additional_code` in for loops
  CHANGELOG.md
  pyccel/codegen/printing/ccode.py
Labels: bug, Ready_for_review, urgent

#2063 Stop limiting the length of strings to 128 characters in Fortran
  CHANGELOG.md
  docs/builtin-functions.md
  docs/type_annotations.md
  pyccel/ast/builtins.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/test_builtins.py
  tests/epyccel/test_epyccel_variable_annotations.py
Labels: Language:Fortran, Ready_for_review

#2065 Fix missing allocations for lists in Fortran
  .github/actions/valgrind_run/action.yml
  pyccel/ast/utilities.py
  pyccel/codegen/printing/fcode.py
  tests/codegen/fcode/test_fcode_codegen.py
  tests/epyccel/test_functionals.py
  tests/epyccel/test_loops.py
Labels: Ready_for_review

#2067 Clean the C-Python API for wrapping function results
  developer_docs/wrapper_stage.md
  pyccel/codegen/wrapper/c_to_python_wrapper.py
Labels: Ready_for_review

#2071 Remove unused symbolic types
  CHANGELOG.md
  pyccel/ast/core.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/base.py
  pyccel/parser/semantic.py
Labels: internals, Ready_for_review

#2073 Add support for `dict.items`
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/builtin_methods/dict_methods.py
  pyccel/ast/builtins.py
  pyccel/ast/class_defs.py
  pyccel/ast/core.py
  pyccel/ast/internals.py
  pyccel/ast/itertoolsext.py
  pyccel/ast/sympy_helper.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/errors/messages.py
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/loops.py
  tests/epyccel/test_epyccel_dicts.py
  tests/epyccel/test_loops.py
Labels: Ready_for_review

#2041 Extend the C min and max functions to more than two variables
  CHANGELOG.md
  pyccel/ast/core.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/utilities.py
  pyccel/stdlib/STC_Extensions/Common_extensions.h
  pyccel/stdlib/STC_Extensions/List_extensions.h
  pyccel/stdlib/STC_Extensions/Set_extensions.h
  tests/epyccel/test_builtins.py
Labels: Ready_to_merge

#2079 Fix translation of classes containing comments
  CHANGELOG.md
  pyccel/parser/syntactic.py
  tests/epyccel/classes/classes_1.py
Labels: Ready_for_review

#2066 Add support for inhomogeneous tuple annotations
  CHANGELOG.md
  docs/type_annotations.md
  pyccel/codegen/printing/ccode.py
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_variable_annotations.py
Labels: Ready_for_review

#2072 Add support for set method intersection #1744
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/builtin_methods/set_methods.py
  pyccel/ast/class_defs.py
  pyccel/parser/syntactic.py
  tests/epyccel/test_epyccel_sets.py
Labels: Ready_to_merge

#2082 Allow the use of a list comprehension to initialise an array
  CHANGELOG.md
  ci_tools/check_pylint_commands.py
  pyccel/ast/functionalexpr.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
Labels: Ready_for_review

#2092 Fix missing prefix in _print_Allocate in FCodePrinter
  pyccel/codegen/printing/fcode.py
Labels: Ready_to_merge

#2090 Update compiler guide reference
  pyccel/codegen/compiling/compilers.py
Labels: Ready_to_merge
