Repository pyccel/pyccel, pull requests merged in 2024-06, with the labels that each got.

#1901 Add Python Support for set initialisation with `set()`
  CHANGELOG.md
  pyccel/ast/builtins.py
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_sets.py
Labels: Ready_to_merge

#1899 Use Python version to make artifact name unique (1 line)
  .github/workflows/linux.yml
Labels: bug, Bot

#1907 Minor coverage bot issue (4 lines)
  ci_tools/coverage_analysis_tools.py
Labels: bug, Ready_for_review, urgent, Bot

#1847 Support variable declarations in c
  CHANGELOG.md
  pyccel/ast/datatypes.py
  pyccel/ast/utilities.py
  pyccel/codegen/codegen.py
  pyccel/codegen/pipeline.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/utilities.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/extensions/__init__.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/array_consts.py
  tests/epyccel/modules/list_comprehension.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_epyccel_modules.py
  tests/epyccel/test_epyccel_variable_annotations.py
  tests/epyccel/test_functionals.py
  tests/epyccel/test_loops.py
Labels: Language:C, Ready_to_merge, Lists, Containers

#1871 Fix minor doc bot issue (6 lines)
  ci_tools/list_docs_tovalidate.py
Labels: documentation, Ready_for_review, urgent, Bot

#1920 Pin NumPy to < 2.0
  CHANGELOG.md
  pyproject.toml
Labels: Ready_for_review, urgent
