Repository pyccel/pyccel, pull requests merged in 2024-04, with the labels that each got.

#1817 Improve Windows install
  .github/actions/windows_install/action.yml
Labels: internals, Ready_to_merge

#1816 Use yaml file instead of deprecated .docstr_coverage file
  .docstr.yaml
  .docstr_coverage
  .github/workflows/docs.yml
Labels: internals, Ready_to_merge

#1822 Fix fstring errors in pyccel.ast
  CHANGELOG.md
  pyccel/ast/core.py
  pyccel/ast/internals.py
  pyccel/ast/numpy_wrapper.py
  pyccel/ast/numpyext.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/pycode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
Labels: internals, Ready_to_merge

#1789 Fix boolean cast in Fortran code
  CHANGELOG.md
  pyccel/ast/builtins.py
  pyccel/ast/datatypes.py
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/modules/python_annotations.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_array_as_func_args.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_epyccel_python_annotations.py
Labels: bug, Ready_to_merge

#1810 Fix array to slice assignment
  CHANGELOG.md
  pyccel/ast/utilities.py
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
Labels: Ready_to_merge

#1824 Filter out cast warnings in cast tests
  CHANGELOG.md
  tests/epyccel/test_arrays.py
Labels: Ready_to_merge

#1825 Remove unused parameters from Assign
  CHANGELOG.md
  pyccel/ast/core.py
Labels: Ready_to_merge

#1812 Remove the FunctionDef, Imports and Classes from CodeBlocks
  CHANGELOG.md
  pyccel/ast/basic.py
  pyccel/ast/core.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/pyccel/scripts/runtest_multiple_results.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#1826 Apply some Pylint fixes, Part 1: Clean up parser
  pyccel/parser/base.py
  pyccel/parser/parser.py
  pyccel/parser/scope.py
  pyccel/parser/syntactic.py
Labels: Ready_to_merge

#1808 Improve non-trivial datatypes
  .dict_custom.txt
  CHANGELOG.md
  developer_docs/ast_nodes.md
  developer_docs/type_inference.md
  docs/ndarrays.md
  pyccel/ast/basic.py
  pyccel/ast/bind_c.py
  pyccel/ast/bitwise_operators.py
  pyccel/ast/builtin_methods/list_methods.py
  pyccel/ast/builtin_methods/set_methods.py
  pyccel/ast/builtins.py
  pyccel/ast/c_concepts.py
  pyccel/ast/cmathext.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/datatypes.py
  pyccel/ast/functionalexpr.py
  pyccel/ast/internals.py
  pyccel/ast/literals.py
  pyccel/ast/macros.py
  pyccel/ast/mathext.py
  pyccel/ast/numpy_wrapper.py
  pyccel/ast/numpyext.py
  pyccel/ast/numpytypes.py
  pyccel/ast/operators.py
  pyccel/ast/sysext.py
  pyccel/ast/type_annotations.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/epyccel/modules/arrays.py
  tests/epyccel/modules/tuples.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_tuples.py
Labels: urgent

#1829 Add a `pyccel.lambdify` function with similar functionality to `sympy.lambdify`
  .dict_custom.txt
  .github/actions/pytest_run/action.yml
  CHANGELOG.md
  docs/quickstart.md
  pyccel/__init__.py
  pyccel/commands/lambdify.py
  pyccel/epyccel.py
  pyproject.toml
  tests/symbolic/mappings.py
  tests/symbolic/test_symbolic.py
Labels: Ready_to_merge

#1837 Clean infer_type function
  CHANGELOG.md
  pyccel/ast/builtins.py
  pyccel/ast/literals.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/tuples.py
  tests/epyccel/test_tuples.py
Labels: Ready_to_merge

#1798 List support: `sort` method
  CHANGELOG.md
  pyccel/ast/builtin_methods/list_methods.py
  pyccel/ast/class_defs.py
  tests/epyccel/test_epyccel_lists.py
  tests/errors/semantic/blocking/SORT_LIST_OPTIONAL_PARAM.py
Labels: Feature, Ready_to_merge, Containers

#1839 Use `PyccelAstNode.pyccel_staging` in `SemanticParser`
  CHANGELOG.md
  pyccel/parser/semantic.py
Labels: Ready_to_merge

#1841 Remove `pyccel.ast.utilities.builtin_function`
  CHANGELOG.md
  developer_docs/ast_nodes.md
  developer_docs/how_to_solve_an_issue.md
  developer_docs/overview.md
  pyccel/ast/builtin_methods/list_methods.py
  pyccel/ast/builtin_methods/set_methods.py
  pyccel/ast/builtins.py
  pyccel/ast/cmathext.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/internals.py
  pyccel/ast/itertoolsext.py
  pyccel/ast/mathext.py
  pyccel/ast/numpyext.py
  pyccel/ast/sysext.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
Labels: Ready_to_merge

#1844 Group and rename_visit functions which receive a FunctionCall
  CHANGELOG.md
  developer_docs/semantic_stage.md
  pyccel/parser/semantic.py
  tests/epyccel/recognised_functions/test_cmath_funcs.py
Labels: Ready_to_merge

#1846 Remove unused/unnecessary functions in `pyccel.parser.utilities`
  CHANGELOG.md
  pyccel/parser/syntactic.py
  pyccel/parser/utilities.py
Labels: Ready_to_merge

#1845 Assert is not a function
  CHANGELOG.md
  pyccel/ast/basic.py
  pyccel/ast/builtins.py
  pyccel/ast/literals.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/errors/errors.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/codegen/ccode/test_ccode_codegen.py
  tests/codegen/fcode/test_fcode_codegen.py
  tests/epyccel/recognised_functions/test_epyccel_pyc_math.py
  tests/epyccel/recognised_functions/test_math_funcs.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_bitwise.py
  tests/epyccel/test_docstrings.py
  tests/epyccel/test_epyccel_pow.py
  tests/epyccel/test_external_functions.py
  tests/epyccel/test_kind.py
  tests/epyccel/test_loops.py
  tests/epyccel/test_pointers.py
  tests/epyccel/test_strings.py
  tests/epyccel/test_tuples.py
  tests/errors/test_errors.py
  tests/external/scripts/lapack/ex1.py
  tests/internal/scripts/lapack/ex1.py
  tests/parser/test_comments.py
  tests/pyccel/test_pyccel.py
  tests/syntax/scripts/asserts.py
  tests/warnings/test_warnings.py
Labels: Ready_to_merge
