Repository pyccel/pyccel, pull requests merged in 2024-09, with the labels that each got.

#1975 Unify import strategy
  .github/workflows/anaconda_linux.yml
  .github/workflows/intel.yml
  .github/workflows/linux.yml
  CHANGELOG.md
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/codeprinter.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
Labels: Ready_for_review

#1941 Rename target to local_alias in AsName
  CHANGELOG.md
  pyccel/ast/core.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
Labels: Ready_for_review

#1902 Add support for DICT popitem
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/builtin_methods/dict_methods.py
  pyccel/ast/class_defs.py
  pyccel/ast/variable.py
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_dicts.py
Labels: Ready_for_review

#1971 Ensure an error is raised when passing the wrong type as an optional argument
  CHANGELOG.md
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  tests/epyccel/test_epyccel_optional_args.py
Labels: Ready_for_review

#1963 Remove use of ndarrays in Fortran array argument wrapping
  CHANGELOG.md
  pyccel/ast/numpy_wrapper.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/stdlib/cwrapper/cwrapper.c
  pyccel/stdlib/cwrapper/cwrapper.h
Labels: Ready_for_review

#1905 Add python support for DICT get method
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/builtin_methods/dict_methods.py
  pyccel/ast/class_defs.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/test_epyccel_dicts.py
Labels: Ready_to_merge

#1981 Fix gFTL installation
  .dict_custom.txt
  .github/actions/check_for_gftl/action.yml
  docs/installation.md
  install_scripts/hook.py
  pyproject.toml
Labels: Ready_for_review

#1984 Add NumPy v2 compatible sign function
  CHANGELOG.md
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/stdlib/math/pyc_math_c.c
  pyccel/stdlib/math/pyc_math_c.h
  pyccel/stdlib/math/pyc_math_f90.f90
  pyccel/stdlib/numpy/numpy_c.c
  pyccel/stdlib/numpy/numpy_c.h
  pyccel/stdlib/numpy/numpy_f90.f90
Labels: Ready_for_review

#1986 fix gcd and lcm implementations
  CHANGELOG.md
  pyccel/stdlib/math/pyc_math_c.c
  pyccel/stdlib/math/pyc_math_f90.f90
  tests/epyccel/recognised_functions/test_epyccel_pyc_math.py
Labels: Ready_to_merge

#1989 Add a temporary warning for nested list
  CHANGELOG.md
  pyccel/ast/datatypes.py
  tests/warnings/semantic/NESTED_LISTS.py
  tests/warnings/test_warnings.py
Labels: Ready_for_review

#1988 Add support for NumPy v2
  .github/workflows/linux.yml
  CHANGELOG.md
  pyccel/ast/numpyext.py
  pyproject.toml
  tests/epyccel/modules/openmp.py
  tests/errors/semantic/non_blocking/INCOMPATIBLE_TYPES_IN_ASSIGNMENT_2.py
  tests/internal/scripts/mpi/bcast.py
Labels: Ready_for_review, next release

#1992 Correct Numpy version check
  pyccel/ast/numpyext.py
  pyproject.toml
Labels: Ready_for_review

#1994 Fix type bugs with NumPy v2
  pyccel/ast/internals.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Ready_to_merge

#1996 Update version information for v1.12.1
  CHANGELOG.md
  pyccel/version.py
Labels: Ready_to_merge

#1997 Set up GitHub release
  .github/workflows/deploy.yml
  CHANGELOG.md
Labels: Ready_to_merge
