Repository pyccel/pyccel, pull requests merged in 2024-07, with the labels that each got.

#1928 Improve Error Message for Missing Target Language Compiler in Pyccel
  AUTHORS
  CHANGELOG.md
  pyccel/codegen/pipeline.py
Labels: Ready_to_merge

#1931 Fix unreleased file lock
  pyccel/codegen/compiling/file_locks.py
  pyccel/codegen/utilities.py
Labels: bug, Ready_for_review, urgent

#1934 Fix code exportation
  CHANGELOG.md
  pyccel/codegen/codegen.py
Labels: Ready_for_review

#1896 [DICT] Add Python support for dict initialisation
  CHANGELOG.md
  ci_tools/check_pylint_commands.py
  pyccel/ast/builtins.py
  pyccel/ast/class_defs.py
  pyccel/ast/datatypes.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/epyccel/test_epyccel_dicts.py
  tests/errors/syntax_blockers/ex1.py
  tests/errors/syntax_errors/dict_str_keys.py
  tests/errors/syntax_errors/import_star.py
Labels: Ready_for_review

#1897 [DICT] Add Python support for dict() function
  CHANGELOG.md
  docs/builtin-functions.md
  docs/type_annotations.md
  pyccel/ast/builtins.py
  pyccel/ast/datatypes.py
  pyccel/ast/numpytypes.py
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_dicts.py
  tests/epyccel/test_epyccel_variable_annotations.py
Labels: Ready_for_review

#1891 [DICT] Add support for pop() method
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/builtin_methods/dict_methods.py
  pyccel/ast/builtin_methods/list_methods.py
  pyccel/ast/builtin_methods/set_methods.py
  pyccel/ast/class_defs.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/test_epyccel_dicts.py
Labels: Ready_for_review

#1864 Remove unnecessary functions from `CodePrinter` (50 lines)
  CHANGELOG.md
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/codeprinter.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/luacode.py
Labels: internals, Ready_for_review

#1936 Add missing C output for inline decorator example
  CHANGELOG.md
  docs/decorators.md
Labels: Ready_for_review

#1872 Correct deployment target for deploy workflow (2 lines)
  .github/workflows/deploy.yml
  CHANGELOG.md
Labels: Ready_for_review, next release

#1938 Optimize substitute method
  CHANGELOG.md
  pyccel/ast/basic.py
Labels: Ready_to_merge

#1950 Correct results type for untransalatable function
  CHANGELOG.md
  pyccel/codegen/wrapper/c_to_python_wrapper.py
Labels: Ready_for_review, urgent

#1953 Bot fixes and improvements
  ci_tools/bot_clean_up.py
  ci_tools/bot_tools/bot_funcs.py
  ci_tools/bot_tools/github_api_interactions.py
Labels: Ready_for_review
