Repository pyccel/pyccel, pull requests merged in 2024-01, with the labels that each got.

#1624 Fix exit statement in Fortran with Intel compiler
  CHANGELOG.md
  pyccel/codegen/printing/fcode.py
  tests/pyccel/scripts/exits/error_message_exit.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#1642 Update docs wrong path
  docs/installation.md
Labels: documentation, Ready_to_merge

#1604 Add wrapping of a FunctionDefResult containing a class
  CHANGELOG.md
  ci_tools/check_slots.py
  pyccel/ast/bind_c.py
  pyccel/ast/c_concepts.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/parser/scope.py
  tests/epyccel/modules/expose_classes.py
  tests/epyccel/test_epyccel_classes.py
Labels: Ready_to_merge, Classes

#1638 Migrate from Setuptools to Hatch to support Python 3.12
  .github/workflows/docs.yml
  .github/workflows/linux.yml
  CHANGELOG.md
  MANIFEST.in
  ci_tools/bot_messages/show_tests.txt
  ci_tools/bot_tools/bot_funcs.py
  install_scripts/__init__.py
  install_scripts/hook.py
  pyproject.toml
  setup.cfg
  setup.py
Labels: Ready_to_merge

#1640 Add `numpy.max` to C printer
  AUTHORS
  CHANGELOG.md
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/stdlib/math/pyc_math_f90.f90
  pyccel/stdlib/ndarrays/ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.h
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Ready_to_merge

#1644 Clean PythonRange printing
  CHANGELOG.md
  developer_docs/codegen_stage.md
  developer_docs/order_docs.md
  docs/decorators.md
  docs/numpy-functions.md
  docs/quickstart.md
  pyccel/codegen/printing/fcode.py
Labels: Ready_to_merge

#1649 Add `numpy.min` to C printer
  CHANGELOG.md
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/stdlib/math/pyc_math_f90.f90
  pyccel/stdlib/ndarrays/ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.h
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Ready_to_merge

#1652 Fix scoping issue
  CHANGELOG.md
  developer_docs/scope.md
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
Labels: Ready_to_merge

#1533 Add missing type error
  CHANGELOG.md
  pyccel/parser/semantic.py
  tests/errors/semantic/blocking/TYPE_ALREADY_DEFINED.py
Labels: Ready_to_merge

#1653 Manage Pylint errors via bot
  .github/workflows/docs.yml
  .github/workflows/pylint.yml
  .pylintrc
  ci_tools/bot_tools/bot_funcs.py
  ci_tools/parse_pylint_output.py
  developer_docs/review_process.md
  tests/epyccel/modules/bitwise.py
Labels: Ready_to_merge, urgent, Bot

#1672 Update Intel environment
  .dict_custom.txt
  .github/actions/intel_install/action.yml
  CHANGELOG.md
  ci_tools/bot_tools/bot_funcs.py
  developer_docs/wrapper_stage.md
  docs/compiler.md
  pyccel/compilers/default_compilers.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_base.py
  tests/epyccel/test_epyccel_classes.py
  tests/epyccel/test_epyccel_mod.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#1673 Use Python 3.10 with new Intel compiler
  .github/workflows/intel.yml
  .github/workflows/pylint.yml
  ci_tools/parse_pylint_output.py
Labels: Ready_to_merge

#1606 Add wrapping of a FunctionDefArgument containing a class
  CHANGELOG.md
  pyccel/ast/cwrapper.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/parser/scope.py
  tests/epyccel/modules/expose_classes.py
  tests/epyccel/test_epyccel_classes.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge, Classes

#1675 Use new class `ast.Constant` to avoid deprecation warnings
  CHANGELOG.md
  pyccel/parser/syntactic.py
Labels: Ready_to_merge

#1679 Fix class type of builtin reduction functions
  pyccel/ast/builtins.py
  tests/epyccel/test_builtins.py
Labels: Ready_to_merge

#1681 Correct wrapper stage link in documentation
  developer_docs/overview.md
Labels: documentation, Ready_to_merge

#1676 Class simplifications
  CHANGELOG.md
  pyccel/ast/class_defs.py
  pyccel/ast/core.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
Labels: Ready_to_merge, Classes

#1685 Allow classes without __init__ functions
  CHANGELOG.md
  pyccel/ast/builtins.py
  pyccel/ast/datatypes.py
  pyccel/ast/numpyext.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/pyccel/scripts/classes/empty_class.py
  tests/pyccel/scripts/runtest_array_type_print.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge, Classes

#1682 Fix name collision issue for class methods
  CHANGELOG.md
  pyccel/ast/core.py
  pyccel/parser/semantic.py
  tests/pyccel/scripts/classes/classes_1.py
Labels: Ready_to_merge, Classes

#1607 Allow calling class methods from Python
  CHANGELOG.md
  pyccel/ast/bind_c.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  tests/epyccel/classes/class_headers.py
  tests/epyccel/classes/class_variables.py
  tests/epyccel/classes/classes.py
  tests/epyccel/classes/classes_1.py
  tests/epyccel/classes/classes_2.py
  tests/epyccel/classes/classes_3.py
  tests/epyccel/classes/classes_4.py
  tests/epyccel/classes/classes_6.py
  tests/epyccel/classes/classes_7.py
  tests/epyccel/classes/generic_methods.py
  tests/epyccel/classes/pep526.py
  tests/epyccel/modules/expose_classes.py
  tests/epyccel/test_epyccel_classes.py
  tests/warnings/test_warnings.py
  tests/warnings/wrapper/HIGH_ORDER_FUNCTIONS_IN_CLASS_FUNCS.py
Labels: Ready_to_merge, Classes

#1704 Make `PythonComplex` a subclass of `PyccelInternalFunction`
  AUTHORS
  pyccel/ast/builtins.py
Labels: enhancement, internals, Ready_to_merge

#1683 Add typing.Final and simplify type inference
  CHANGELOG.md
  ci_tools/coverage_analysis_tools.py
  docs/supported-libraries.md
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/datatypes.py
  pyccel/ast/headers.py
  pyccel/ast/internals.py
  pyccel/ast/type_annotations.py
  pyccel/ast/typingext.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/commands/pyccel_init.py
  pyccel/parser/grammar/headers.tx
  pyccel/parser/grammar/types.tx
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/parser/syntax/headers.py
  tests/epyccel/test_array_as_func_args.py
  tests/epyccel/test_epyccel_headers.py
  tests/epyccel/test_epyccel_variable_annotations.py
Labels: Ready_to_merge, Type specification
