Repository pyccel/pyccel, pull requests merged in 2024-03, with the labels that each got.

#1776 Fix pytest error following deprecation
  CHANGELOG.md
  pyproject.toml
  tests/ndarrays/conftest.py
Labels: Ready_for_review, urgent

#1780 Fix partial templates
  CHANGELOG.md
  pyccel/parser/semantic.py
  pyccel/version.py
  tests/epyccel/test_epyccel_decorators.py
Labels: Ready_to_merge, next release

#1764 Set support : clear method
  CHANGELOG.md
  pyccel/ast/builtin_methods/set_methods.py
  pyccel/ast/class_defs.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/test_epyccel_sets.py
Labels: Ready_to_merge, Language:Python, urgent, Containers

#1784 Mark the failing Intel test
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Ready_to_merge

#1731 List support: extend method
  CHANGELOG.md
  pyccel/ast/builtin_methods/list_methods.py
  pyccel/ast/class_defs.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/list_class_attr.py
  tests/epyccel/modules/list_user_defined_objs1.py
  tests/epyccel/modules/list_user_defined_objs2.py
  tests/epyccel/test_epyccel_lists.py
  tests/errors/semantic/blocking/EXTEND_LIST_INCOMPATIBLE_TYPES_0.py
  tests/errors/semantic/blocking/EXTEND_LIST_INCOMPATIBLE_TYPES_1.py
  tests/errors/semantic/blocking/EXTEND_LIST_INCOMPATIBLE_TYPES_2.py
Labels: Feature, Ready_to_merge, Containers

#1728 Annotate functions when they are called
  CHANGELOG.md
  docs/decorators.md
  pyccel/ast/basic.py
  pyccel/ast/core.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/epyccel.py
  pyccel/parser/extend_tree.py
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
  pyccel/parser/utilities.py
  pyccel/utilities/strings.py
  pyproject.toml
  tests/epyccel/modules/function_call_before_definition.py
  tests/epyccel/modules/function_call_before_definition_2.py
  tests/epyccel/modules/multi_rank.py
  tests/epyccel/test_epyccel_multi_rank.py
  tests/epyccel/test_function_call_before_definition.py
  tests/errors/semantic/blocking/INCOMPATIBLE_ARGUMENT3.py
  tests/errors/semantic/blocking/functions_in_uniontype.py
  tests/pyccel/scripts/decorators_inline.py
  tests/pyccel/scripts/functions.py
Labels: bug, internals, Ready_to_merge

#1791 Clean up unnecessary arguments in the codegen stage
  CHANGELOG.md
  pyccel/codegen/codegen.py
  pyccel/codegen/pipeline.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/luacode.py
  pyccel/codegen/printing/pycode.py
  pyccel/codegen/python_wrapper.py
  pyccel/commands/console.py
  tests/codegen/ccode/test_ccode_codegen.py
  tests/codegen/fcode/test_fcode_codegen.py
  tests/codegen/pycode/test_pycode_codegen.py
  tests/errors/test_errors.py
  tests/symbolic/test_symbolic.py
  tests/warnings/test_warnings.py
Labels: internals, Ready_to_merge

#1793 Fix array unpacking
  CHANGELOG.md
  pyccel/codegen/printing/ccode.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
Labels: Ready_to_merge

#1772 Set support: `pop` method
  CHANGELOG.md
  pyccel/ast/builtin_methods/set_methods.py
  pyccel/ast/class_defs.py
  tests/epyccel/test_epyccel_sets.py
Labels: Ready_to_merge, Language:Python, Containers

#1790 List support: `remove` method
  CHANGELOG.md
  pyccel/ast/builtin_methods/list_methods.py
  pyccel/ast/class_defs.py
  tests/epyccel/test_epyccel_lists.py
Labels: Feature, Ready_to_merge, Containers

#1766 Set support: `remove` method
  CHANGELOG.md
  pyccel/ast/builtin_methods/set_methods.py
  pyccel/ast/class_defs.py
  tests/epyccel/test_epyccel_sets.py
  tests/errors/semantic/blocking/REMOVE_SET_INCOMPATIBLE_TYPES_1.py
  tests/errors/semantic/blocking/REMOVE_SET_INCOMPATIBLE_TYPES_2.py
  tests/errors/semantic/blocking/REMOVE_SET_KEYERROR_TYPE_1.py
Labels: Ready_to_merge, Language:Python, Containers

#1762 Support array copy between different datatypes (#1641)
  AUTHORS
  CHANGELOG.md
  pyccel/stdlib/ndarrays/ndarrays.c
  tests/epyccel/modules/arrays.py
  tests/epyccel/test_arrays.py
Labels: Ready_to_merge

#1797 List support: `copy` method
  CHANGELOG.md
  pyccel/ast/builtin_methods/list_methods.py
  pyccel/ast/class_defs.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/test_epyccel_lists.py
Labels: Feature, Ready_to_merge, Containers
