Repository pyccel/pyccel, pull requests merged in 2024-10, with the labels that each got.

#1999 Fix test failures with Intel compiler
  CHANGELOG.md
  pyccel/ast/builtins.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/recognised_functions/test_numpy_types.py
Labels: Ready_to_merge

#2003 Flag `I` as a conflicting variable name
  CHANGELOG.md
  pyccel/naming/cnameclashchecker.py
  pyccel/naming/languagenameclashchecker.py
  tests/epyccel/modules/consts.py
  tests/epyccel/test_epyccel_modules.py
Labels: Ready_to_merge

#1976 Add Fortran support for list declarations
  CHANGELOG.md
  pyccel/ast/c_concepts.py
  pyccel/ast/core.py
  pyccel/ast/fortran_concepts.py
  pyccel/ast/low_level_tools.py
  pyccel/ast/numpyext.py
  pyccel/codegen/pipeline.py
  pyccel/codegen/printing/codeprinter.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/utilities.py
  tests/codegen/fcode/test_fcode_codegen.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_epyccel_IfTernaryOperator.py
  tests/epyccel/test_epyccel_variable_annotations.py
  tests/epyccel/test_functionals.py
  tests/epyccel/test_loops.py
  tests/pyccel/test_pyccel.py
Labels: Ready_for_review

#1908 Add C and Fortran support for `len()` function
  CHANGELOG.md
  pyccel/ast/builtins.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  tests/conftest.py
  tests/epyccel/test_builtins.py
  tests/epyccel/test_epyccel_lists.py
  tests/epyccel/test_epyccel_variable_annotations.py
Labels: Ready_for_review

#1982 Add support for list.append method
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/test_epyccel_lists.py
Labels: Ready_to_merge

#2004 Add Fortran support for set initialisation
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/builtins.py
  pyccel/codegen/pipeline.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/utilities.py
  pyccel/stdlib/tools/pyc_tools_f90.f90
  tests/epyccel/test_epyccel_sets.py
  tests/epyccel/test_epyccel_variable_annotations.py
Labels: Ready_for_review

#2005 Add Fortran support for dict initialisation
  pyccel/ast/builtins.py
  pyccel/ast/low_level_tools.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/test_epyccel_variable_annotations.py
Labels: Ready_for_review

#1922 [SET] Add c support for `add`
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/test_epyccel_sets.py
Labels: Ready_for_review

#1923 [SET] Add c support for `clear`
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/test_epyccel_sets.py
Labels: Ready_for_review

#2014 Add Fortran support for set method `pop`
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/low_level_tools.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/codegen/utilities.py
  pyccel/stdlib/gFTL_functions/Set_extensions.inc
  pyproject.toml
  tests/epyccel/test_epyccel_sets.py
Labels: Ready_for_review

#1850 Allow homogeneous tuples as function arguments
  CHANGELOG.md
  developer_docs/wrapper_stage.md
  docs/type_annotations.md
  pyccel/ast/bind_c.py
  pyccel/ast/cwrapper.py
  pyccel/ast/datatypes.py
  pyccel/ast/type_annotations.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/parser/semantic.py
  tests/epyccel/test_tuples.py
Labels: Ready_to_merge, Containers

#2019 Add support for set.copy
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/test_epyccel_sets.py
Labels: Ready_for_review

#2020 Simplify function call creation
  CHANGELOG.md
  pyccel/ast/core.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/parser/semantic.py
Labels: Ready_for_review

#2015 Add support for set method `union`
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/builtin_methods/set_methods.py
  pyccel/ast/class_defs.py
  pyccel/ast/core.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/stdlib/STC_Extensions/Set_extensions.h
  tests/epyccel/test_epyccel_sets.py
  tests/errors/semantic/blocking/SET_UNION_TYPES.py
Labels: Ready_for_review, Containers

#2028 Optimise min/max to avoid unnecessary temporary variables
  AUTHORS
  CHANGELOG.md
  pyccel/codegen/printing/ccode.py
  tests/epyccel/test_builtins.py
Labels: Ready_to_merge

#2027 Fix missing loop in slice assignment
  CHANGELOG.md
  pyccel/ast/utilities.py
  tests/epyccel/modules/arrays.py
Labels: Ready_for_review

#2017 Add support for `in` operator
  CHANGELOG.md
  pyccel/ast/operators.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/epyccel/test_epyccel_dicts.py
  tests/epyccel/test_epyccel_lists.py
  tests/epyccel/test_epyccel_sets.py
  tests/pyccel/scripts/classes/class_magic.py
  tests/pyccel/test_pyccel.py
Labels: needs_initial_review, Containers
