Repository pyccel/pyccel, pull requests merged in 2025-06, with the labels that each got.

#2324 Complete deprecation of real as a type annotation
  pyccel/parser/semantic.py
  tests/epyccel/modules/generic_functions.py
  tests/errors/semantic/blocking/INTERFACE_WRONG_TYPES.py
  tests/errors/semantic/blocking/REAL_TYPE.py
  tests/errors/semantic/blocking/TEMPLATE_WRONG_TYPE_CALL.py
  tests/errors/semantic/blocking/functions_in_uniontype.py
  tests/errors/syntax_errors/TEMPLATE_WRONG_KEY.py
  tests/errors/syntax_errors/TEMPLATE_WRONG_NUMBER_ARGS.py
Labels: Ready_to_merge

#2328 Fix GCC-15 warnings
  CHANGELOG.md
  pyccel/ast/operators.py
  pyccel/codegen/pipeline.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/utilities.py
Labels: Ready_to_merge

#2318 Replace .pyh files in stdlib/ with .pyi files
  CHANGELOG.md
  docs/header-files.md
  pyccel/ast/class_defs.py
  pyccel/ast/core.py
  pyccel/ast/typingext.py
  pyccel/parser/semantic.py
  pyccel/stdlib/internal/blas.pyh
  pyccel/stdlib/internal/blas.pyi
  pyccel/stdlib/internal/dfftpack.pyh
  pyccel/stdlib/internal/dfftpack.pyi
  pyccel/stdlib/internal/fftw.pyh
  pyccel/stdlib/internal/fftw.pyi
  pyccel/stdlib/internal/fitpack.pyh
  pyccel/stdlib/internal/fitpack.pyi
  pyccel/stdlib/internal/hdf5.pyh
  pyccel/stdlib/internal/hdf5.pyi
  pyccel/stdlib/internal/lapack.pyh
  pyccel/stdlib/internal/lapack.pyi
  pyccel/stdlib/internal/mpi.pyh
  pyccel/stdlib/internal/mpi.pyi
  pyccel/stdlib/internal/openacc.pyh
  pyccel/stdlib/internal/openacc.pyi
  pyccel/stdlib/internal/openmp.pyh
  pyccel/stdlib/internal/openmp.pyi
  pyproject.toml
Labels: Ready_to_merge

#2331 Deprecate `@template` decorator
  CHANGELOG.md
  developer_docs/wrapper_stage.md
  docs/classes.md
  docs/header-files.md
  docs/quickstart.md
  pyccel/ast/core.py
  pyccel/ast/headers.py
  pyccel/ast/typingext.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/commands/epyccel.py
  pyccel/commands/lambdify.py
  pyccel/decorators.py
  pyccel/errors/messages.py
  pyccel/parser/grammar/headers.tx
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/parser/syntax/headers.py
  tests/epyccel/test_epyccel_context_clues.py
  tests/errors/semantic/blocking/functions_in_type_alias.py
  tests/errors/semantic/blocking/functions_in_uniontype.py
  tests/pyccel/scripts/runtest_stub.pyi
  tests/symbolic/test_symbolic.py
Labels: Ready_to_merge

#2334 Use metavars to ensure compilation dependencies are known for imports
  CHANGELOG.md
  pyccel/codegen/codegen.py
  pyccel/codegen/pipeline.py
  pyccel/parser/parser.py
  tests/pyccel/scripts/pyccel_generated_compilation_dependency.py
  tests/pyccel/scripts/runtest_pyccel_generated_compilation_dependency.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#2336 Add CI for markdown
  .dict_custom.txt
  .github/workflows/markdown_lint.yml
  .markdownlint.json
  CHANGELOG.md
  README.md
  ci_tools/bot_messages/show_tests.txt
  ci_tools/bot_tools/bot_funcs.py
  developer_docs/ast_nodes.md
  developer_docs/codegen_stage.md
  developer_docs/development_conventions.md
  developer_docs/getting_started.md
  developer_docs/order_docs.md
  developer_docs/overview.md
  developer_docs/review_process.md
  developer_docs/scope.md
  developer_docs/semantic_stage.md
  developer_docs/syntactic_stage.md
  developer_docs/tips_and_tricks.md
  developer_docs/type_inference.md
  developer_docs/wrapper_stage.md
  docs/builtin-functions.md
  docs/classes.md
  docs/compiler.md
  docs/const_keyword.md
  docs/containers.md
  docs/decorators.md
  docs/function-pointers-as-arguments.md
  docs/header-files.md
  docs/installation.md
  docs/openmp.md
  docs/quickstart.md
  docs/supported-libraries.md
  docs/type_annotations.md
Labels: Ready_to_merge

#2330 Improve inline handling
  CHANGELOG.md
  docs/decorators.md
  pyccel/ast/basic.py
  pyccel/ast/core.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
  tests/errors/semantic/blocking/INCOMPATIBLE_ARGUMENT3.py
  tests/errors/semantic/non_blocking/is.py
  tests/errors/semantic/non_blocking/var_is_none.py
  tests/pyccel/scripts/decorators_inline.py
  tests/pyccel/test_pyccel.py
Labels: next release

#2347 Remove undocumented, untested, obsolete Lua printer
  .dict_custom.txt
  CHANGELOG.md
  pyccel/codegen/printing/luacode.py
Labels: Ready_to_merge

#2346 Add verbosity levels to Pyccel
  CHANGELOG.md
  pyccel/codegen/codegen.py
  pyccel/codegen/compiling/compilers.py
  pyccel/codegen/pipeline.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/codeprinter.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/codegen/python_wrapper.py
  pyccel/codegen/utilities.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/codegen/wrapper/wrapper.py
  pyccel/commands/console.py
  pyccel/commands/epyccel.py
  pyccel/complexity/basic.py
  pyccel/errors/errors.py
  pyccel/parser/base.py
  pyccel/parser/parser.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/ast/test_basic.py
  tests/codegen/ccode/test_ccode_codegen.py
  tests/codegen/fcode/test_fcode_codegen.py
  tests/codegen/pycode/test_pycode_codegen.py
  tests/epyccel/test_arrays_multiple_assignments.py
  tests/epyccel/test_epyccel_args.py
  tests/epyccel/test_epyccel_functions.py
  tests/epyccel/test_epyccel_optional_args.py
  tests/errors/test_errors.py
  tests/parser/test_comments.py
  tests/preprocess/test_preprocess.py
  tests/semantic/test_semantic.py
  tests/syntax/test_syntax.py
  tests/warnings/test_warnings.py
Labels: Ready_to_merge, next release

#2354 Fix Import regression
  pyccel/parser/semantic.py
  tests/pyccel/scripts/runtest_import_mod_project_as.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#2293 Add `pyccel-test` command to run unit tests. Improve docs
  .github/actions/pytest_parallel/action.yml
  .github/workflows/linux_pyccel-test_cmd.yml
  README.md
  ci_tools/bot_messages/show_tests.txt
  ci_tools/bot_tools/bot_funcs.py
  docs/installation.md
  docs/source/index.rst
  docs/testing.md
  pyccel/commands/pyccel_test.py
  pyproject.toml
  pytest.ini
  tests/conftest.py
  tests/epyccel/test_mpi_collective.py
  tests/epyccel/test_mpi_point_to_point.py
  tests/epyccel/test_parallel_epyccel.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge, next release

#2358 Add support for bitwise operators with NumPy arrays
  CHANGELOG.md
  pyccel/ast/bitwise_operators.py
  pyccel/ast/numpyext.py
  pyccel/ast/numpytypes.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  tests/epyccel/recognised_functions/test_numpy_operators.py
Labels: Ready_to_merge

#2360 CI fixes
  .github/workflows/docs.yml
  .github/workflows/linux_pyccel-test_cmd.yml
  .github/workflows/markdown_lint.yml
  ci_tools/bot_tools/github_api_interactions.py
  pyccel/ast/bind_c.py
  pyccel/ast/bitwise_operators.py
  pyccel/ast/builtin_methods/set_methods.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/headers.py
  pyccel/ast/numpy_wrapper.py
  pyccel/ast/numpyext.py
  pyccel/ast/operators.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/commands/epyccel.py
  pyccel/commands/pyccel_test.py
  pyccel/parser/extend_tree.py
  pyccel/parser/semantic.py
  pyccel/parser/syntax/headers.py
Labels: Ready_to_merge, next release

#2361 Add a test to check if deployment is working
  .dict_custom.txt
  .github/workflows/deploy.yml
  .github/workflows/deploy_check.yml
  CHANGELOG.md
  pyproject.toml
Labels: Ready_to_merge, next release

#2365 Update changelog following version release
  CHANGELOG.md
  pyccel/version.py
Labels: Ready_to_merge

#2366 Fix the use of the `--export-compiler-config` flag.
  CHANGELOG.md
  pyccel/codegen/compiling/compilers.py
  pyccel/commands/console.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge
