Repository pyccel/pyccel, pull requests merged in 2025-02, with the labels that each got.

#2184 Add support for dict.keys
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/builtin_methods/dict_methods.py
  pyccel/ast/class_defs.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_dicts.py
Labels: Ready_for_review, Containers

#2170 Add support for set initialisation from other objects
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/builtins.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_sets.py
Labels: Ready_for_review

#2186 Allow saving an array result of a function to a slice
  .dict_custom.txt
  CHANGELOG.md
  pyccel/parser/semantic.py
  tests/pyccel/scripts/return_numpy_arrays.py
  tests/pyccel/test_pyccel.py
  tests/warnings/semantic/UNNECESSARY_ALLOCATION_IN_FUNCTION.py
Labels: Ready_for_review

#2188 Remove pickle
  .github/workflows/pickle.yml
  .github/workflows/pickle_wheel.yml
  .pylintrc
  CHANGELOG.md
  ci_tools/bot_messages/show_tests.txt
  ci_tools/bot_tools/bot_funcs.py
  ci_tools/devel_branch_tests.py
  ci_tools/wait_for_main_workflows.py
  install_scripts/hook.py
  pyccel/ast/core.py
  pyccel/ast/datatypes.py
  pyccel/ast/headers.py
  pyccel/ast/low_level_tools.py
  pyccel/ast/numpytypes.py
  pyccel/ast/omp.py
  pyccel/ast/variable.py
  pyccel/commands/pyccel_init.py
  pyccel/parser/base.py
  pyccel/parser/extend_tree.py
  pyccel/parser/syntactic.py
  pyproject.toml
Labels: Ready_for_review

#2185 Add preliminary support for `isinstance`
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/operators.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  tests/epyccel/test_base.py
  tests/epyccel/test_builtins.py
  tests/pyccel/test_pyccel.py
Labels: Ready_for_review

#2191 Fix missing pointer assignment error
  CHANGELOG.md
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
  tests/errors/semantic/non_blocking/INCOMPATIBLE_TYPES_IN_ASSIGNMENT_6.py
  tests/errors/semantic/non_blocking/INCOMPATIBLE_TYPES_IN_ASSIGNMENT_7.py
Labels: Ready_for_review

#2131 Allow returning strings from functions
  CHANGELOG.md
  docs/type_annotations.md
  pyccel/ast/bind_c.py
  pyccel/ast/c_concepts.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/datatypes.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  tests/epyccel/modules/strings_module.py
  tests/epyccel/test_strings.py
Labels: Ready_for_review

#2180 Fix shape of multi-level containers
  .gitignore
  CHANGELOG.md
  developer_docs/ast_nodes.md
  developer_docs/type_inference.md
  pyccel/ast/bind_c.py
  pyccel/ast/builtin_methods/dict_methods.py
  pyccel/ast/builtins.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/datatypes.py
  pyccel/ast/internals.py
  pyccel/ast/numpyext.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/parser/semantic.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_builtins.py
Labels: Ready_for_review

#2201 Improve error handling
  CHANGELOG.md
  developer_docs/overview.md
  developer_docs/tips_and_tricks.md
  pyccel/codegen/printing/codeprinter.py
  pyccel/codegen/wrapper/wrapper.py
  pyccel/errors/messages.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/errors/semantic/blocking/INTERNAL_ERROR.py
Labels: Ready_for_review

#2205 Remove unused class `FuncAddressDeclare`
  CHANGELOG.md
  pyccel/ast/core.py
  pyccel/codegen/printing/ccode.py
Labels: Ready_for_review

#2208 Add compile time analysis of if blocks
  CHANGELOG.md
  pyccel/ast/sympy_helper.py
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_compile_time_if.py
Labels: Ready_for_review

#2199 Fix saving an empty string
  CHANGELOG.md
  pyccel/codegen/printing/fcode.py
  tests/epyccel/modules/strings_module.py
Labels: Ready_for_review

#2196 Fix string comparison
  CHANGELOG.md
  pyccel/ast/datatypes.py
  pyccel/ast/operators.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/test_strings.py
Labels: Ready_for_review

#2197 Allow strings as dictionary keys in C
  CHANGELOG.md
  docs/type_annotations.md
  pyccel/codegen/printing/ccode.py
  tests/epyccel/test_epyccel_dicts.py
  tests/epyccel/test_epyccel_lists.py
Labels: Ready_for_review

#2142 improve floordiv translation
  CHANGELOG.md
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/stdlib/math/pyc_math_c.c
  pyccel/stdlib/math/pyc_math_c.h
  pyccel/stdlib/math/pyc_math_f90.f90
  tests/epyccel/test_epyccel_division.py
Labels: Ready_to_merge

#2222 Improve citation data
  AUTHORS
  CITATION.cff
Labels: Ready_to_merge

#2211 Add missing libraries in intel installation
  .github/actions/intel_install/action.yml
  tests/epyccel/modules/openmp.py
  tests/epyccel/test_epyccel_openmp.py
Labels: Ready_to_merge

#2223 Bump Anaconda windows version to avoid installation problems
  .github/workflows/anaconda_windows.yml
  ci_tools/bot_tools/bot_funcs.py
Labels: Ready_to_merge

#2225 Improve compiler documentation
  docs/compiler.md
  pyccel/commands/console.py
Labels: Ready_to_merge

#2226 Fix Anaconda Windows CI
  .github/workflows/anaconda_windows.yml
Labels: Ready_to_merge

#2227 Correct error message formatting for invalid type annotation
  pyccel/ast/type_annotations.py
Labels: Ready_to_merge

#2219 Add support for `__getitem__`
  CHANGELOG.md
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  tests/epyccel/classes/class_magic.py
  tests/epyccel/test_epyccel_classes.py
Labels: Ready_to_merge

#2179 Allow returning tuples from functions
  CHANGELOG.md
  docs/type_annotations.md
  pyccel/ast/bind_c.py
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/ast/datatypes.py
  pyccel/ast/headers.py
  pyccel/ast/literals.py
  pyccel/ast/numpy_wrapper.py
  pyccel/ast/type_annotations.py
  pyccel/ast/utilities.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/parser/base.py
  pyccel/parser/grammar/headers.tx
  pyccel/parser/grammar/types.tx
  pyccel/parser/scope.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  pyccel/parser/syntax/headers.py
  pyccel/stdlib/internal/openmp.pyh
  tests/codegen/fcode/scripts/headers.py
  tests/codegen/fcode/scripts/multiple_assign.py
  tests/epyccel/modules/highorder_functions.py
  tests/epyccel/modules/tuples.py
  tests/epyccel/test_arrays_multiple_assignments.py
  tests/epyccel/test_epyccel_decorators.py
  tests/epyccel/test_tuples.py
  tests/errors/semantic/blocking/INCOMPATIBLE_TYPES_IN_ASSIGNMENT_5.py
  tests/errors/test_errors.py
  tests/pyccel/scripts/functions.py
  tests/pyccel/test_pyccel.py
Labels: Ready_to_merge

#2107 Fix swap
  .dict_custom.txt
  CHANGELOG.md
  pyccel/ast/basic.py
  pyccel/ast/datatypes.py
  pyccel/errors/errors.py
  pyccel/parser/semantic.py
  tests/epyccel/test_arrays_multiple_assignments.py
  tests/epyccel/test_epyccel_expressions.py
  tests/errors/semantic/non_blocking/COMPLICATED_SWAP.py
Labels: Ready_to_merge
