Repository pyccel/pyccel, pull requests merged in 2025-03, with the labels that each got.

#2230 Fix annotation of variables that are returned in a function whose result type is annotated
  CHANGELOG.md
  pyccel/ast/type_annotations.py
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_functions.py
Labels: Ready_to_merge

#2171 Add `min/max` support for `Lists` and `Sets`
  pyccel/ast/builtins.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/utilities.py
  pyccel/stdlib/STC_Extensions/List_extensions.h
  pyccel/stdlib/STC_Extensions/Set_extensions.h
  pyccel/stdlib/gFTL_functions/Set_extensions.inc
  pyccel/stdlib/gFTL_functions/Vector_extensions.inc
  tests/epyccel/test_builtins.py
  tests/epyccel/test_epyccel_lists.py
  tests/epyccel/test_epyccel_sets.py
Labels: Ready_to_merge

#2231 Add support for `set.isdisjoint`
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/builtin_methods/set_methods.py
  pyccel/ast/class_defs.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/stdlib/STC_Extensions/Set_extensions.h
  pyccel/stdlib/gFTL_functions/Set_extensions.inc
  tests/epyccel/test_epyccel_sets.py
Labels: Ready_to_merge

#2239 Specify the libdirs for a shared Python library
  CHANGELOG.md
  pyccel/compilers/default_compilers.py
Labels: Ready_to_merge

#2238 Fix incorrect memory handling for temporary variable
  CHANGELOG.md
  pyccel/codegen/printing/ccode.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
Labels: Ready_for_review

#2245 Fix shape type error
  CHANGELOG.md
  pyccel/ast/variable.py
  tests/errors/semantic/non_blocking/LIST_OF_TUPLES.py
Labels: Ready_for_review

#2244 Fix minor bugs on the devel branch
  pyccel/stdlib/gFTL_functions/Set_extensions.inc
  tests/epyccel/test_epyccel_expressions.py
Labels: Ready_for_review

#2234 Print 'const' in c where appropriate
  CHANGELOG.md
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
Labels: Ready_for_review

#2246 Fix underflow errors on devel
  tests/epyccel/test_epyccel_expressions.py
Labels: Ready_for_review

#1977 Improve list comprehension
  CHANGELOG.md
  pyccel/ast/datatypes.py
  pyccel/ast/functionalexpr.py
  pyccel/ast/literals.py
  pyccel/ast/numpytypes.py
  pyccel/ast/sympy_helper.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  pyccel/parser/syntactic.py
  tests/epyccel/modules/functionals.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_epyccel_generators.py
  tests/epyccel/test_functionals.py
Labels: Ready_to_merge, urgent

#2250 Use Fortran and C native expressions for min/max values
  pyccel/ast/datatypes.py
  pyccel/ast/functionalexpr.py
  pyccel/ast/literals.py
  pyccel/ast/numpytypes.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_generators.py
Labels: Ready_for_review

#2249 Improve installation docs and recommend virtual environment
  .dict_custom.txt
  CHANGELOG.md
  README.md
  docs/installation.md
  docs/quickstart.md
Labels: Ready_to_merge

#2255 Improve issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/coverage.md
  .github/ISSUE_TEMPLATE/coverage.yaml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/ISSUE_TEMPLATE/improvement.yaml
  .github/ISSUE_TEMPLATE/installation-problem.md
  .github/ISSUE_TEMPLATE/installation-problem.yaml
  .github/ISSUE_TEMPLATE/other.yaml
  AUTHORS
Labels: Ready_to_merge

#2200 Allow passing strings as arguments
  CHANGELOG.md
  docs/builtin-functions.md
  docs/type_annotations.md
  pyccel/ast/builtins.py
  pyccel/ast/cwrapper.py
  pyccel/ast/literals.py
  pyccel/ast/variable.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  tests/epyccel/modules/strings_module.py
  tests/epyccel/test_strings.py
Labels: Ready_to_merge

#2256 Add `C` and `Fortran` support for the `list.clear()` method.
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/test_epyccel_lists.py
Labels: Ready_to_merge

#2252 Describe multiple compilers in the same JSON file
  CHANGELOG.md
  docs/compiler.md
  pyccel/codegen/compiling/compilers.py
  pyccel/codegen/pipeline.py
  pyccel/codegen/python_wrapper.py
  pyccel/codegen/utilities.py
  pyccel/commands/console.py
  pyccel/commands/epyccel.py
  pyccel/compilers/default_compilers.py
Labels: Ready_to_merge

#2258 Add the necessary pointer information to ensure errors are raised for multi-level containers
  .github/actions/pytest_run/action.yml
  CHANGELOG.md
  pyccel/ast/variable.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/epyccel/modules/list_user_defined_objs.py
  tests/epyccel/modules/list_user_defined_objs1.py
  tests/epyccel/modules/list_user_defined_objs2.py
  tests/epyccel/modules/loops.py
  tests/epyccel/test_epyccel_lists.py
  tests/epyccel/test_loops.py
  tests/errors/semantic/non_blocking/RETURN_LIST_ELEMENT.py
  tests/errors/semantic/non_blocking/RETURN_NON_OWNING_LIST.py
  tests/errors/semantic/non_blocking/RETURN_NON_OWNING_LIST2.py
  tests/errors/semantic/non_blocking/RETURN_NON_OWNING_LIST3.py
  tests/errors/semantic/non_blocking/RETURN_NON_OWNING_LIST4.py
  tests/errors/semantic/non_blocking/RETURN_NON_OWNING_LIST_ELEMENT.py
Labels: Ready_to_merge
