Repository pyccel/pyccel, pull requests merged in 2025-01, with the labels that each got.

#996 Issue #983 | Add Round function and implement the conversion to C, Fortran, and Python
  AUTHORS
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/ast/builtins.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/commands/console.py
  pyccel/commands/epyccel.py
  pyccel/stdlib/math/pyc_math_c.c
  pyccel/stdlib/math/pyc_math_c.h
  pyccel/stdlib/math/pyc_math_f90.f90
  tests/epyccel/test_builtins.py
Labels: enhancement, Language:C, Language:Fortran, needs_initial_review

#2128 Add wrapping support for arithmetic magic methods
  CHANGELOG.md
  docs/classes.md
  pyccel/ast/core.py
  pyccel/ast/cwrapper.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/printing/pycode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/parser/syntactic.py
  tests/epyccel/classes/class_magic.py
  tests/epyccel/test_epyccel_classes.py
Labels: Ready_for_review

#2124 Remove deprecated type specifiers in tests
  CHANGELOG.md
  pyccel/ast/builtins.py
  pyccel/ast/numpytypes.py
  pyccel/ast/operators.py
  pyccel/ast/type_annotations.py
  pyccel/parser/semantic.py
  tests/epyccel/classes/class_headers.py
  tests/epyccel/modules/Module_9.py
  tests/epyccel/modules/generic_functions.py
  tests/epyccel/modules/generic_functions_2.py
  tests/epyccel/modules/highorder_functions.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_epyccel_headers.py
  tests/errors/codegen/fortran_non_blocking/issue_1339.py
  tests/errors/semantic/blocking/DECORATOR_WRONG_NUMBER_TYPES.py
  tests/errors/semantic/blocking/HEADER_WRONG_NUMBER_TYPES.py
  tests/errors/semantic/blocking/MISSING_TYPE_ALIAS.py
  tests/errors/semantic/blocking/RECURSIVE_RESULTS_REQUIRED_header.py
  tests/errors/semantic/blocking/functions_in_template.py
  tests/errors/semantic/blocking/functions_in_type_alias.py
  tests/errors/semantic/blocking/functions_in_uniontype.py
  tests/errors/semantic/non_blocking/CONST_ASSIGNED_ARGUMENT.py
  tests/errors/semantic/non_blocking/CONST_ASSIGNED_ARGUMENT2.py
  tests/errors/semantic/non_blocking/UNION_RETURN_TYPE_headers.py
  tests/errors/semantic/non_blocking/UNION_RETURN_TYPE_types.py
  tests/errors/syntax_errors/DECORATOR_WRONG_NUMBER_TYPES.py
  tests/errors/syntax_errors/HEADER_WRONG_NUMBER_TYPES.py
  tests/errors/syntax_errors/functions_in_template.py
  tests/errors/syntax_errors/types_arg.py
  tests/errors/syntax_errors/types_arg_type.py
  tests/parser/test_headers.py
  tests/pyccel/scripts/classes/class_headers.py
  tests/pyccel/scripts/generic_functions.py
  tests/pyccel/scripts/hope_benchmarks/fib.py
  tests/pyccel/scripts/hope_benchmarks/hope_fib.py
  tests/pyccel/scripts/hope_benchmarks/hope_ln_python.py
  tests/pyccel/scripts/hope_benchmarks/hope_pairwise_python.py
  tests/pyccel/scripts/hope_benchmarks/point_spread_func.py
  tests/pyccel/scripts/hope_benchmarks/quicksort.py
  tests/pyccel/scripts/hope_benchmarks/simplify.py
  tests/pyccel/scripts/hope_benchmarks_decorators/hope_ln_python.py
  tests/pyccel/scripts/hope_benchmarks_decorators/hope_pairwise_python.py
  tests/pyccel/scripts/hope_benchmarks_decorators/point_spread_func.py
  tests/pyccel/scripts/hope_benchmarks_decorators/quicksort.py
  tests/pyccel/scripts/hope_benchmarks_decorators/simplify.py
  tests/pyccel/scripts/import_syntax/from_mod_import.py
  tests/pyccel/scripts/import_syntax/from_mod_import_as.py
  tests/pyccel/scripts/import_syntax/from_mod_import_as_func.py
  tests/pyccel/scripts/import_syntax/from_mod_import_func.py
  tests/pyccel/scripts/import_syntax/import_mod.py
  tests/pyccel/scripts/import_syntax/import_mod_as.py
  tests/pyccel/scripts/import_syntax/import_mod_as_func.py
  tests/pyccel/scripts/import_syntax/import_mod_func.py
  tests/pyccel/test_pyccel.py
  tests/semantic/scripts/functions.py
  tests/symbolic/scripts/decorator.py
  tests/syntax/scripts/Functional_Stmts.py
  tests/syntax/scripts/annotated_comments.py
Labels: Ready_for_review

#2114 Fix multiple calls to `_build_gFTL_extension_module`
  pyccel/codegen/printing/fcode.py
  tests/epyccel/modules/Module_11.py
  tests/epyccel/test_epyccel_modules.py
Labels: Ready_for_review

#2118 Add C and Fortran support for remove/discard
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  tests/epyccel/test_epyccel_sets.py
Labels: Ready_for_review

#2129 Add support for `_len__`
  CHANGELOG.md
  docs/classes.md
  pyccel/ast/builtins.py
  pyccel/ast/cwrapper.py
  pyccel/ast/itertoolsext.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/parser/semantic.py
  tests/epyccel/classes/class_magic.py
  tests/epyccel/test_epyccel_classes.py
  tests/pyccel/scripts/classes/class_magic.py
  tests/pyccel/test_pyccel.py
Labels: Ready_for_review

#2140 Fix removal of `test_node` when `rhs.current_user_node` becomes `PyccelAssociativeParenthesis`
  CHANGELOG.md
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_generators.py
Labels: Ready_to_merge

#2136 Use older cmake command line syntax for compatibility
  docs/installation.md
  install_scripts/hook.py
Labels: Ready_for_review

#2138 Fix bug in `get_strides_and_shape_from_numpy_array`
  .github/actions/pytest_run/action.yml
  pyccel/codegen/pipeline.py
  pyccel/commands/console.py
  pyccel/commands/epyccel.py
  pyccel/stdlib/cwrapper/cwrapper.c
  pyccel/stdlib/math/pyc_math_c.c
  pyccel/stdlib/math/pyc_math_c.h
  tests/epyccel/modules/arrays.py
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_base.py
  tests/pyccel/test_pyccel.py
Labels: Ready_for_review, urgent

#2147 Remove unnecessary compilation step
  CHANGELOG.md
  pyccel/codegen/python_wrapper.py
  pyccel/codegen/utilities.py
Labels: Ready_for_review, blocked

#2146 Fix class constness
  docs/classes.md
  pyccel/ast/core.py
  pyccel/ast/numpyext.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/fcode.py
  pyccel/parser/semantic.py
  tests/epyccel/classes/class_constness.py
  tests/epyccel/test_epyccel_classes.py
Labels: Ready_for_review

#2155 Fix intel compilation
  CHANGELOG.md
  pyccel/ast/bind_c.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  pyccel/compilers/default_compilers.py
  pyccel/naming/fortrannameclashchecker.py
  pyccel/stdlib/cwrapper/cwrapper.c
  tests/epyccel/test_epyccel_classes.py
Labels: Ready_for_review

#2143 Add C support for `dict.pop`
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/utilities.py
  pyccel/stdlib/STC_Extensions/Dict_extensions.h
  tests/epyccel/test_epyccel_dicts.py
Labels: Ready_to_merge

#2154 Fix missing line information when an unknown class method is called
  CHANGELOG.md
  pyccel/ast/core.py
  pyccel/ast/variable.py
  pyccel/parser/semantic.py
Labels: Ready_for_review

#2160 Add C support for `dict.clear`
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/codegen/printing/ccode.py
  tests/epyccel/test_epyccel_dicts.py
Labels: Ready_to_merge

#2151 Fix use of `_additional_code` in If condition
  CHANGELOG.md
  pyccel/codegen/printing/ccode.py
  tests/epyccel/test_builtins.py
Labels: Ready_for_review

#2165 Add Fortran support for `dict.clear`
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/codegen/printing/fcode.py
  tests/epyccel/test_epyccel_dicts.py
Labels: needs_initial_review

#2168 Improve `STC` extensions imports
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/utilities.py
Labels: Ready_to_merge

#2157 Remove BindCFunctionDefResult
  .docstr.yaml
  .pylintrc
  CHANGELOG.md
  ci_tools/list_docs_tovalidate.py
  ci_tools/process_results.py
  developer_docs/wrapper_stage.md
  pyccel/ast/bind_c.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/codegen/wrapper/fortran_to_c_wrapper.py
  tests/epyccel/test_tuples.py
Labels: Ready_for_review

#1969 Replace ndarrays with STC's cspan
  .dict_custom.txt
  .github/actions/pytest_run/action.yml
  .github/actions/pytest_run_python/action.yml
  CHANGELOG.md
  developer_docs/codegen_stage.md
  developer_docs/order_docs.md
  developer_docs/wrapper_stage.md
  docs/classes.md
  docs/decorators.md
  docs/ndarrays.md
  docs/numpy-functions.md
  pyccel/ast/cwrapper.py
  pyccel/ast/internals.py
  pyccel/ast/low_level_tools.py
  pyccel/ast/numpy_wrapper.py
  pyccel/ast/utilities.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/utilities.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/errors/messages.py
  pyccel/naming/cnameclashchecker.py
  pyccel/stdlib/STC_Extensions/CSpan_extensions.h
  pyccel/stdlib/cwrapper/cwrapper.c
  pyccel/stdlib/cwrapper/cwrapper.h
  pyccel/stdlib/cwrapper_ndarrays/cwrapper_ndarrays.c
  pyccel/stdlib/cwrapper_ndarrays/cwrapper_ndarrays.h
  pyccel/stdlib/math/pyc_math_c.c
  pyccel/stdlib/math/pyc_math_c.h
  pyccel/stdlib/ndarrays/ndarrays.c
  pyccel/stdlib/ndarrays/ndarrays.h
  tests/epyccel/recognised_functions/test_numpy_funcs.py
  tests/epyccel/test_arrays.py
  tests/epyccel/test_arrays_multiple_assignments.py
  tests/ndarrays/conftest.py
  tests/ndarrays/leaks_check.py
  tests/ndarrays/test_ndarrays.c
  tests/pyccel/test_pyccel.py
Labels: Ready_for_review

#2174 Add C support for `dict.get`
  CHANGELOG.md
  docs/builtin-functions.md
  pyccel/codegen/printing/ccode.py
  tests/epyccel/test_epyccel_dicts.py
Labels: Ready_to_merge

#2172 Restore developer mode for tests
  CHANGELOG.md
  developer_docs/tips_and_tricks.md
  pyccel/commands/console.py
  pyccel/commands/epyccel.py
  tests/conftest.py
Labels: Ready_for_review

#2169 Fix warnings about constness
  pyccel/ast/cwrapper.py
  pyccel/codegen/printing/cwrappercode.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  pyccel/compilers/default_compilers.py
  pyccel/stdlib/cwrapper/cwrapper.c
Labels: Ready_for_review

#2158 Allow returning a dictionary from C
  CHANGELOG.md
  pyccel/ast/cwrapper.py
  pyccel/codegen/wrapper/c_to_python_wrapper.py
  tests/epyccel/test_epyccel_dicts.py
Labels: Ready_for_review

#2164 Add support for `dict.__getitem__`
  CHANGELOG.md
  pyccel/ast/builtin_methods/dict_methods.py
  pyccel/ast/class_defs.py
  pyccel/codegen/printing/ccode.py
  pyccel/codegen/printing/fcode.py
  pyccel/codegen/printing/pycode.py
  pyccel/parser/semantic.py
  tests/epyccel/test_epyccel_dicts.py
Labels: Ready_for_review
